/*
GetHook API

Webhook Reliability Gateway — accept inbound webhooks, persist them durably, forward to destinations, retry failures, and replay past events.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gethook

import (
	"encoding/json"
)

// checks if the UpsertBrandSettingsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpsertBrandSettingsRequest{}

// UpsertBrandSettingsRequest struct for UpsertBrandSettingsRequest
type UpsertBrandSettingsRequest struct {
	CompanyName *string `json:"company_name,omitempty"`
	DocsTitle *string `json:"docs_title,omitempty"`
	LogoUrl *string `json:"logo_url,omitempty"`
	PrimaryColor *string `json:"primary_color,omitempty"`
	SupportEmail *string `json:"support_email,omitempty"`
}

// NewUpsertBrandSettingsRequest instantiates a new UpsertBrandSettingsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpsertBrandSettingsRequest() *UpsertBrandSettingsRequest {
	this := UpsertBrandSettingsRequest{}
	return &this
}

// NewUpsertBrandSettingsRequestWithDefaults instantiates a new UpsertBrandSettingsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpsertBrandSettingsRequestWithDefaults() *UpsertBrandSettingsRequest {
	this := UpsertBrandSettingsRequest{}
	return &this
}

// GetCompanyName returns the CompanyName field value if set, zero value otherwise.
func (o *UpsertBrandSettingsRequest) GetCompanyName() string {
	if o == nil || IsNil(o.CompanyName) {
		var ret string
		return ret
	}
	return *o.CompanyName
}

// GetCompanyNameOk returns a tuple with the CompanyName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpsertBrandSettingsRequest) GetCompanyNameOk() (*string, bool) {
	if o == nil || IsNil(o.CompanyName) {
		return nil, false
	}
	return o.CompanyName, true
}

// HasCompanyName returns a boolean if a field has been set.
func (o *UpsertBrandSettingsRequest) HasCompanyName() bool {
	if o != nil && !IsNil(o.CompanyName) {
		return true
	}

	return false
}

// SetCompanyName gets a reference to the given string and assigns it to the CompanyName field.
func (o *UpsertBrandSettingsRequest) SetCompanyName(v string) {
	o.CompanyName = &v
}

// GetDocsTitle returns the DocsTitle field value if set, zero value otherwise.
func (o *UpsertBrandSettingsRequest) GetDocsTitle() string {
	if o == nil || IsNil(o.DocsTitle) {
		var ret string
		return ret
	}
	return *o.DocsTitle
}

// GetDocsTitleOk returns a tuple with the DocsTitle field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpsertBrandSettingsRequest) GetDocsTitleOk() (*string, bool) {
	if o == nil || IsNil(o.DocsTitle) {
		return nil, false
	}
	return o.DocsTitle, true
}

// HasDocsTitle returns a boolean if a field has been set.
func (o *UpsertBrandSettingsRequest) HasDocsTitle() bool {
	if o != nil && !IsNil(o.DocsTitle) {
		return true
	}

	return false
}

// SetDocsTitle gets a reference to the given string and assigns it to the DocsTitle field.
func (o *UpsertBrandSettingsRequest) SetDocsTitle(v string) {
	o.DocsTitle = &v
}

// GetLogoUrl returns the LogoUrl field value if set, zero value otherwise.
func (o *UpsertBrandSettingsRequest) GetLogoUrl() string {
	if o == nil || IsNil(o.LogoUrl) {
		var ret string
		return ret
	}
	return *o.LogoUrl
}

// GetLogoUrlOk returns a tuple with the LogoUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpsertBrandSettingsRequest) GetLogoUrlOk() (*string, bool) {
	if o == nil || IsNil(o.LogoUrl) {
		return nil, false
	}
	return o.LogoUrl, true
}

// HasLogoUrl returns a boolean if a field has been set.
func (o *UpsertBrandSettingsRequest) HasLogoUrl() bool {
	if o != nil && !IsNil(o.LogoUrl) {
		return true
	}

	return false
}

// SetLogoUrl gets a reference to the given string and assigns it to the LogoUrl field.
func (o *UpsertBrandSettingsRequest) SetLogoUrl(v string) {
	o.LogoUrl = &v
}

// GetPrimaryColor returns the PrimaryColor field value if set, zero value otherwise.
func (o *UpsertBrandSettingsRequest) GetPrimaryColor() string {
	if o == nil || IsNil(o.PrimaryColor) {
		var ret string
		return ret
	}
	return *o.PrimaryColor
}

// GetPrimaryColorOk returns a tuple with the PrimaryColor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpsertBrandSettingsRequest) GetPrimaryColorOk() (*string, bool) {
	if o == nil || IsNil(o.PrimaryColor) {
		return nil, false
	}
	return o.PrimaryColor, true
}

// HasPrimaryColor returns a boolean if a field has been set.
func (o *UpsertBrandSettingsRequest) HasPrimaryColor() bool {
	if o != nil && !IsNil(o.PrimaryColor) {
		return true
	}

	return false
}

// SetPrimaryColor gets a reference to the given string and assigns it to the PrimaryColor field.
func (o *UpsertBrandSettingsRequest) SetPrimaryColor(v string) {
	o.PrimaryColor = &v
}

// GetSupportEmail returns the SupportEmail field value if set, zero value otherwise.
func (o *UpsertBrandSettingsRequest) GetSupportEmail() string {
	if o == nil || IsNil(o.SupportEmail) {
		var ret string
		return ret
	}
	return *o.SupportEmail
}

// GetSupportEmailOk returns a tuple with the SupportEmail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpsertBrandSettingsRequest) GetSupportEmailOk() (*string, bool) {
	if o == nil || IsNil(o.SupportEmail) {
		return nil, false
	}
	return o.SupportEmail, true
}

// HasSupportEmail returns a boolean if a field has been set.
func (o *UpsertBrandSettingsRequest) HasSupportEmail() bool {
	if o != nil && !IsNil(o.SupportEmail) {
		return true
	}

	return false
}

// SetSupportEmail gets a reference to the given string and assigns it to the SupportEmail field.
func (o *UpsertBrandSettingsRequest) SetSupportEmail(v string) {
	o.SupportEmail = &v
}

func (o UpsertBrandSettingsRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpsertBrandSettingsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CompanyName) {
		toSerialize["company_name"] = o.CompanyName
	}
	if !IsNil(o.DocsTitle) {
		toSerialize["docs_title"] = o.DocsTitle
	}
	if !IsNil(o.LogoUrl) {
		toSerialize["logo_url"] = o.LogoUrl
	}
	if !IsNil(o.PrimaryColor) {
		toSerialize["primary_color"] = o.PrimaryColor
	}
	if !IsNil(o.SupportEmail) {
		toSerialize["support_email"] = o.SupportEmail
	}
	return toSerialize, nil
}

type NullableUpsertBrandSettingsRequest struct {
	value *UpsertBrandSettingsRequest
	isSet bool
}

func (v NullableUpsertBrandSettingsRequest) Get() *UpsertBrandSettingsRequest {
	return v.value
}

func (v *NullableUpsertBrandSettingsRequest) Set(val *UpsertBrandSettingsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpsertBrandSettingsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpsertBrandSettingsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpsertBrandSettingsRequest(val *UpsertBrandSettingsRequest) *NullableUpsertBrandSettingsRequest {
	return &NullableUpsertBrandSettingsRequest{value: val, isSet: true}
}

func (v NullableUpsertBrandSettingsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpsertBrandSettingsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


