/*
GetHook API

Webhook Reliability Gateway — accept inbound webhooks, persist them durably, forward to destinations, retry failures, and replay past events.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gethook

import (
	"encoding/json"
)

// checks if the PlatformStats type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PlatformStats{}

// PlatformStats struct for PlatformStats
type PlatformStats struct {
	DeliveryAttempts *int32 `json:"delivery_attempts,omitempty"`
	EventsDelivered *int32 `json:"events_delivered,omitempty"`
	EventsProcessed *int32 `json:"events_processed,omitempty"`
	SuccessRatePct *float32 `json:"success_rate_pct,omitempty"`
}

// NewPlatformStats instantiates a new PlatformStats object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPlatformStats() *PlatformStats {
	this := PlatformStats{}
	return &this
}

// NewPlatformStatsWithDefaults instantiates a new PlatformStats object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPlatformStatsWithDefaults() *PlatformStats {
	this := PlatformStats{}
	return &this
}

// GetDeliveryAttempts returns the DeliveryAttempts field value if set, zero value otherwise.
func (o *PlatformStats) GetDeliveryAttempts() int32 {
	if o == nil || IsNil(o.DeliveryAttempts) {
		var ret int32
		return ret
	}
	return *o.DeliveryAttempts
}

// GetDeliveryAttemptsOk returns a tuple with the DeliveryAttempts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlatformStats) GetDeliveryAttemptsOk() (*int32, bool) {
	if o == nil || IsNil(o.DeliveryAttempts) {
		return nil, false
	}
	return o.DeliveryAttempts, true
}

// HasDeliveryAttempts returns a boolean if a field has been set.
func (o *PlatformStats) HasDeliveryAttempts() bool {
	if o != nil && !IsNil(o.DeliveryAttempts) {
		return true
	}

	return false
}

// SetDeliveryAttempts gets a reference to the given int32 and assigns it to the DeliveryAttempts field.
func (o *PlatformStats) SetDeliveryAttempts(v int32) {
	o.DeliveryAttempts = &v
}

// GetEventsDelivered returns the EventsDelivered field value if set, zero value otherwise.
func (o *PlatformStats) GetEventsDelivered() int32 {
	if o == nil || IsNil(o.EventsDelivered) {
		var ret int32
		return ret
	}
	return *o.EventsDelivered
}

// GetEventsDeliveredOk returns a tuple with the EventsDelivered field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlatformStats) GetEventsDeliveredOk() (*int32, bool) {
	if o == nil || IsNil(o.EventsDelivered) {
		return nil, false
	}
	return o.EventsDelivered, true
}

// HasEventsDelivered returns a boolean if a field has been set.
func (o *PlatformStats) HasEventsDelivered() bool {
	if o != nil && !IsNil(o.EventsDelivered) {
		return true
	}

	return false
}

// SetEventsDelivered gets a reference to the given int32 and assigns it to the EventsDelivered field.
func (o *PlatformStats) SetEventsDelivered(v int32) {
	o.EventsDelivered = &v
}

// GetEventsProcessed returns the EventsProcessed field value if set, zero value otherwise.
func (o *PlatformStats) GetEventsProcessed() int32 {
	if o == nil || IsNil(o.EventsProcessed) {
		var ret int32
		return ret
	}
	return *o.EventsProcessed
}

// GetEventsProcessedOk returns a tuple with the EventsProcessed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlatformStats) GetEventsProcessedOk() (*int32, bool) {
	if o == nil || IsNil(o.EventsProcessed) {
		return nil, false
	}
	return o.EventsProcessed, true
}

// HasEventsProcessed returns a boolean if a field has been set.
func (o *PlatformStats) HasEventsProcessed() bool {
	if o != nil && !IsNil(o.EventsProcessed) {
		return true
	}

	return false
}

// SetEventsProcessed gets a reference to the given int32 and assigns it to the EventsProcessed field.
func (o *PlatformStats) SetEventsProcessed(v int32) {
	o.EventsProcessed = &v
}

// GetSuccessRatePct returns the SuccessRatePct field value if set, zero value otherwise.
func (o *PlatformStats) GetSuccessRatePct() float32 {
	if o == nil || IsNil(o.SuccessRatePct) {
		var ret float32
		return ret
	}
	return *o.SuccessRatePct
}

// GetSuccessRatePctOk returns a tuple with the SuccessRatePct field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlatformStats) GetSuccessRatePctOk() (*float32, bool) {
	if o == nil || IsNil(o.SuccessRatePct) {
		return nil, false
	}
	return o.SuccessRatePct, true
}

// HasSuccessRatePct returns a boolean if a field has been set.
func (o *PlatformStats) HasSuccessRatePct() bool {
	if o != nil && !IsNil(o.SuccessRatePct) {
		return true
	}

	return false
}

// SetSuccessRatePct gets a reference to the given float32 and assigns it to the SuccessRatePct field.
func (o *PlatformStats) SetSuccessRatePct(v float32) {
	o.SuccessRatePct = &v
}

func (o PlatformStats) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PlatformStats) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DeliveryAttempts) {
		toSerialize["delivery_attempts"] = o.DeliveryAttempts
	}
	if !IsNil(o.EventsDelivered) {
		toSerialize["events_delivered"] = o.EventsDelivered
	}
	if !IsNil(o.EventsProcessed) {
		toSerialize["events_processed"] = o.EventsProcessed
	}
	if !IsNil(o.SuccessRatePct) {
		toSerialize["success_rate_pct"] = o.SuccessRatePct
	}
	return toSerialize, nil
}

type NullablePlatformStats struct {
	value *PlatformStats
	isSet bool
}

func (v NullablePlatformStats) Get() *PlatformStats {
	return v.value
}

func (v *NullablePlatformStats) Set(val *PlatformStats) {
	v.value = val
	v.isSet = true
}

func (v NullablePlatformStats) IsSet() bool {
	return v.isSet
}

func (v *NullablePlatformStats) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePlatformStats(val *PlatformStats) *NullablePlatformStats {
	return &NullablePlatformStats{value: val, isSet: true}
}

func (v NullablePlatformStats) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePlatformStats) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


