/*
GetHook API

Webhook Reliability Gateway — accept inbound webhooks, persist them durably, forward to destinations, retry failures, and replay past events.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gethook

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Route type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Route{}

// Route struct for Route
type Route struct {
	AccountId string `json:"account_id"`
	Active bool `json:"active"`
	CreatedAt string `json:"created_at"`
	DestinationId string `json:"destination_id"`
	EventTypePattern *string `json:"event_type_pattern,omitempty"`
	Id string `json:"id"`
	RetryPolicy map[string]interface{} `json:"retry_policy"`
	SourceId *string `json:"source_id,omitempty"`
}

type _Route Route

// NewRoute instantiates a new Route object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRoute(accountId string, active bool, createdAt string, destinationId string, id string, retryPolicy map[string]interface{}) *Route {
	this := Route{}
	this.AccountId = accountId
	this.Active = active
	this.CreatedAt = createdAt
	this.DestinationId = destinationId
	this.Id = id
	this.RetryPolicy = retryPolicy
	return &this
}

// NewRouteWithDefaults instantiates a new Route object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRouteWithDefaults() *Route {
	this := Route{}
	return &this
}

// GetAccountId returns the AccountId field value
func (o *Route) GetAccountId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value
// and a boolean to check if the value has been set.
func (o *Route) GetAccountIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccountId, true
}

// SetAccountId sets field value
func (o *Route) SetAccountId(v string) {
	o.AccountId = v
}

// GetActive returns the Active field value
func (o *Route) GetActive() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Active
}

// GetActiveOk returns a tuple with the Active field value
// and a boolean to check if the value has been set.
func (o *Route) GetActiveOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Active, true
}

// SetActive sets field value
func (o *Route) SetActive(v bool) {
	o.Active = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *Route) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *Route) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *Route) SetCreatedAt(v string) {
	o.CreatedAt = v
}

// GetDestinationId returns the DestinationId field value
func (o *Route) GetDestinationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DestinationId
}

// GetDestinationIdOk returns a tuple with the DestinationId field value
// and a boolean to check if the value has been set.
func (o *Route) GetDestinationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DestinationId, true
}

// SetDestinationId sets field value
func (o *Route) SetDestinationId(v string) {
	o.DestinationId = v
}

// GetEventTypePattern returns the EventTypePattern field value if set, zero value otherwise.
func (o *Route) GetEventTypePattern() string {
	if o == nil || IsNil(o.EventTypePattern) {
		var ret string
		return ret
	}
	return *o.EventTypePattern
}

// GetEventTypePatternOk returns a tuple with the EventTypePattern field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Route) GetEventTypePatternOk() (*string, bool) {
	if o == nil || IsNil(o.EventTypePattern) {
		return nil, false
	}
	return o.EventTypePattern, true
}

// HasEventTypePattern returns a boolean if a field has been set.
func (o *Route) HasEventTypePattern() bool {
	if o != nil && !IsNil(o.EventTypePattern) {
		return true
	}

	return false
}

// SetEventTypePattern gets a reference to the given string and assigns it to the EventTypePattern field.
func (o *Route) SetEventTypePattern(v string) {
	o.EventTypePattern = &v
}

// GetId returns the Id field value
func (o *Route) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *Route) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *Route) SetId(v string) {
	o.Id = v
}

// GetRetryPolicy returns the RetryPolicy field value
func (o *Route) GetRetryPolicy() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.RetryPolicy
}

// GetRetryPolicyOk returns a tuple with the RetryPolicy field value
// and a boolean to check if the value has been set.
func (o *Route) GetRetryPolicyOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.RetryPolicy, true
}

// SetRetryPolicy sets field value
func (o *Route) SetRetryPolicy(v map[string]interface{}) {
	o.RetryPolicy = v
}

// GetSourceId returns the SourceId field value if set, zero value otherwise.
func (o *Route) GetSourceId() string {
	if o == nil || IsNil(o.SourceId) {
		var ret string
		return ret
	}
	return *o.SourceId
}

// GetSourceIdOk returns a tuple with the SourceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Route) GetSourceIdOk() (*string, bool) {
	if o == nil || IsNil(o.SourceId) {
		return nil, false
	}
	return o.SourceId, true
}

// HasSourceId returns a boolean if a field has been set.
func (o *Route) HasSourceId() bool {
	if o != nil && !IsNil(o.SourceId) {
		return true
	}

	return false
}

// SetSourceId gets a reference to the given string and assigns it to the SourceId field.
func (o *Route) SetSourceId(v string) {
	o.SourceId = &v
}

func (o Route) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Route) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["account_id"] = o.AccountId
	toSerialize["active"] = o.Active
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["destination_id"] = o.DestinationId
	if !IsNil(o.EventTypePattern) {
		toSerialize["event_type_pattern"] = o.EventTypePattern
	}
	toSerialize["id"] = o.Id
	toSerialize["retry_policy"] = o.RetryPolicy
	if !IsNil(o.SourceId) {
		toSerialize["source_id"] = o.SourceId
	}
	return toSerialize, nil
}

func (o *Route) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"account_id",
		"active",
		"created_at",
		"destination_id",
		"id",
		"retry_policy",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRoute := _Route{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRoute)

	if err != nil {
		return err
	}

	*o = Route(varRoute)

	return err
}

type NullableRoute struct {
	value *Route
	isSet bool
}

func (v NullableRoute) Get() *Route {
	return v.value
}

func (v *NullableRoute) Set(val *Route) {
	v.value = val
	v.isSet = true
}

func (v NullableRoute) IsSet() bool {
	return v.isSet
}

func (v *NullableRoute) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRoute(val *Route) *NullableRoute {
	return &NullableRoute{value: val, isSet: true}
}

func (v NullableRoute) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRoute) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


