/*
GetHook API

Webhook Reliability Gateway — accept inbound webhooks, persist them durably, forward to destinations, retry failures, and replay past events.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gethook

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateSourceRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateSourceRequest{}

// CreateSourceRequest struct for CreateSourceRequest
type CreateSourceRequest struct {
	AuthMode *string `json:"auth_mode,omitempty"`
	Name string `json:"name"`
	VerificationConfig map[string]interface{} `json:"verification_config,omitempty"`
}

type _CreateSourceRequest CreateSourceRequest

// NewCreateSourceRequest instantiates a new CreateSourceRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateSourceRequest(name string) *CreateSourceRequest {
	this := CreateSourceRequest{}
	this.Name = name
	return &this
}

// NewCreateSourceRequestWithDefaults instantiates a new CreateSourceRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateSourceRequestWithDefaults() *CreateSourceRequest {
	this := CreateSourceRequest{}
	return &this
}

// GetAuthMode returns the AuthMode field value if set, zero value otherwise.
func (o *CreateSourceRequest) GetAuthMode() string {
	if o == nil || IsNil(o.AuthMode) {
		var ret string
		return ret
	}
	return *o.AuthMode
}

// GetAuthModeOk returns a tuple with the AuthMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSourceRequest) GetAuthModeOk() (*string, bool) {
	if o == nil || IsNil(o.AuthMode) {
		return nil, false
	}
	return o.AuthMode, true
}

// HasAuthMode returns a boolean if a field has been set.
func (o *CreateSourceRequest) HasAuthMode() bool {
	if o != nil && !IsNil(o.AuthMode) {
		return true
	}

	return false
}

// SetAuthMode gets a reference to the given string and assigns it to the AuthMode field.
func (o *CreateSourceRequest) SetAuthMode(v string) {
	o.AuthMode = &v
}

// GetName returns the Name field value
func (o *CreateSourceRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateSourceRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateSourceRequest) SetName(v string) {
	o.Name = v
}

// GetVerificationConfig returns the VerificationConfig field value if set, zero value otherwise.
func (o *CreateSourceRequest) GetVerificationConfig() map[string]interface{} {
	if o == nil || IsNil(o.VerificationConfig) {
		var ret map[string]interface{}
		return ret
	}
	return o.VerificationConfig
}

// GetVerificationConfigOk returns a tuple with the VerificationConfig field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSourceRequest) GetVerificationConfigOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.VerificationConfig) {
		return map[string]interface{}{}, false
	}
	return o.VerificationConfig, true
}

// HasVerificationConfig returns a boolean if a field has been set.
func (o *CreateSourceRequest) HasVerificationConfig() bool {
	if o != nil && !IsNil(o.VerificationConfig) {
		return true
	}

	return false
}

// SetVerificationConfig gets a reference to the given map[string]interface{} and assigns it to the VerificationConfig field.
func (o *CreateSourceRequest) SetVerificationConfig(v map[string]interface{}) {
	o.VerificationConfig = v
}

func (o CreateSourceRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateSourceRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AuthMode) {
		toSerialize["auth_mode"] = o.AuthMode
	}
	toSerialize["name"] = o.Name
	if !IsNil(o.VerificationConfig) {
		toSerialize["verification_config"] = o.VerificationConfig
	}
	return toSerialize, nil
}

func (o *CreateSourceRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateSourceRequest := _CreateSourceRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateSourceRequest)

	if err != nil {
		return err
	}

	*o = CreateSourceRequest(varCreateSourceRequest)

	return err
}

type NullableCreateSourceRequest struct {
	value *CreateSourceRequest
	isSet bool
}

func (v NullableCreateSourceRequest) Get() *CreateSourceRequest {
	return v.value
}

func (v *NullableCreateSourceRequest) Set(val *CreateSourceRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateSourceRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateSourceRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateSourceRequest(val *CreateSourceRequest) *NullableCreateSourceRequest {
	return &NullableCreateSourceRequest{value: val, isSet: true}
}

func (v NullableCreateSourceRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateSourceRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


