/*
GetHook API

Webhook Reliability Gateway — accept inbound webhooks, persist them durably, forward to destinations, retry failures, and replay past events.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gethook

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateDestinationRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateDestinationRequest{}

// CreateDestinationRequest struct for CreateDestinationRequest
type CreateDestinationRequest struct {
	AuthConfig map[string]interface{} `json:"auth_config,omitempty"`
	CustomHeaders map[string]interface{} `json:"custom_headers,omitempty"`
	Name string `json:"name"`
	SigningSecret *string `json:"signing_secret,omitempty"`
	TimeoutSeconds *int32 `json:"timeout_seconds,omitempty"`
	Url string `json:"url"`
}

type _CreateDestinationRequest CreateDestinationRequest

// NewCreateDestinationRequest instantiates a new CreateDestinationRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateDestinationRequest(name string, url string) *CreateDestinationRequest {
	this := CreateDestinationRequest{}
	this.Name = name
	this.Url = url
	return &this
}

// NewCreateDestinationRequestWithDefaults instantiates a new CreateDestinationRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateDestinationRequestWithDefaults() *CreateDestinationRequest {
	this := CreateDestinationRequest{}
	return &this
}

// GetAuthConfig returns the AuthConfig field value if set, zero value otherwise.
func (o *CreateDestinationRequest) GetAuthConfig() map[string]interface{} {
	if o == nil || IsNil(o.AuthConfig) {
		var ret map[string]interface{}
		return ret
	}
	return o.AuthConfig
}

// GetAuthConfigOk returns a tuple with the AuthConfig field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateDestinationRequest) GetAuthConfigOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.AuthConfig) {
		return map[string]interface{}{}, false
	}
	return o.AuthConfig, true
}

// HasAuthConfig returns a boolean if a field has been set.
func (o *CreateDestinationRequest) HasAuthConfig() bool {
	if o != nil && !IsNil(o.AuthConfig) {
		return true
	}

	return false
}

// SetAuthConfig gets a reference to the given map[string]interface{} and assigns it to the AuthConfig field.
func (o *CreateDestinationRequest) SetAuthConfig(v map[string]interface{}) {
	o.AuthConfig = v
}

// GetCustomHeaders returns the CustomHeaders field value if set, zero value otherwise.
func (o *CreateDestinationRequest) GetCustomHeaders() map[string]interface{} {
	if o == nil || IsNil(o.CustomHeaders) {
		var ret map[string]interface{}
		return ret
	}
	return o.CustomHeaders
}

// GetCustomHeadersOk returns a tuple with the CustomHeaders field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateDestinationRequest) GetCustomHeadersOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.CustomHeaders) {
		return map[string]interface{}{}, false
	}
	return o.CustomHeaders, true
}

// HasCustomHeaders returns a boolean if a field has been set.
func (o *CreateDestinationRequest) HasCustomHeaders() bool {
	if o != nil && !IsNil(o.CustomHeaders) {
		return true
	}

	return false
}

// SetCustomHeaders gets a reference to the given map[string]interface{} and assigns it to the CustomHeaders field.
func (o *CreateDestinationRequest) SetCustomHeaders(v map[string]interface{}) {
	o.CustomHeaders = v
}

// GetName returns the Name field value
func (o *CreateDestinationRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateDestinationRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateDestinationRequest) SetName(v string) {
	o.Name = v
}

// GetSigningSecret returns the SigningSecret field value if set, zero value otherwise.
func (o *CreateDestinationRequest) GetSigningSecret() string {
	if o == nil || IsNil(o.SigningSecret) {
		var ret string
		return ret
	}
	return *o.SigningSecret
}

// GetSigningSecretOk returns a tuple with the SigningSecret field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateDestinationRequest) GetSigningSecretOk() (*string, bool) {
	if o == nil || IsNil(o.SigningSecret) {
		return nil, false
	}
	return o.SigningSecret, true
}

// HasSigningSecret returns a boolean if a field has been set.
func (o *CreateDestinationRequest) HasSigningSecret() bool {
	if o != nil && !IsNil(o.SigningSecret) {
		return true
	}

	return false
}

// SetSigningSecret gets a reference to the given string and assigns it to the SigningSecret field.
func (o *CreateDestinationRequest) SetSigningSecret(v string) {
	o.SigningSecret = &v
}

// GetTimeoutSeconds returns the TimeoutSeconds field value if set, zero value otherwise.
func (o *CreateDestinationRequest) GetTimeoutSeconds() int32 {
	if o == nil || IsNil(o.TimeoutSeconds) {
		var ret int32
		return ret
	}
	return *o.TimeoutSeconds
}

// GetTimeoutSecondsOk returns a tuple with the TimeoutSeconds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateDestinationRequest) GetTimeoutSecondsOk() (*int32, bool) {
	if o == nil || IsNil(o.TimeoutSeconds) {
		return nil, false
	}
	return o.TimeoutSeconds, true
}

// HasTimeoutSeconds returns a boolean if a field has been set.
func (o *CreateDestinationRequest) HasTimeoutSeconds() bool {
	if o != nil && !IsNil(o.TimeoutSeconds) {
		return true
	}

	return false
}

// SetTimeoutSeconds gets a reference to the given int32 and assigns it to the TimeoutSeconds field.
func (o *CreateDestinationRequest) SetTimeoutSeconds(v int32) {
	o.TimeoutSeconds = &v
}

// GetUrl returns the Url field value
func (o *CreateDestinationRequest) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *CreateDestinationRequest) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *CreateDestinationRequest) SetUrl(v string) {
	o.Url = v
}

func (o CreateDestinationRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateDestinationRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AuthConfig) {
		toSerialize["auth_config"] = o.AuthConfig
	}
	if !IsNil(o.CustomHeaders) {
		toSerialize["custom_headers"] = o.CustomHeaders
	}
	toSerialize["name"] = o.Name
	if !IsNil(o.SigningSecret) {
		toSerialize["signing_secret"] = o.SigningSecret
	}
	if !IsNil(o.TimeoutSeconds) {
		toSerialize["timeout_seconds"] = o.TimeoutSeconds
	}
	toSerialize["url"] = o.Url
	return toSerialize, nil
}

func (o *CreateDestinationRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateDestinationRequest := _CreateDestinationRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateDestinationRequest)

	if err != nil {
		return err
	}

	*o = CreateDestinationRequest(varCreateDestinationRequest)

	return err
}

type NullableCreateDestinationRequest struct {
	value *CreateDestinationRequest
	isSet bool
}

func (v NullableCreateDestinationRequest) Get() *CreateDestinationRequest {
	return v.value
}

func (v *NullableCreateDestinationRequest) Set(val *CreateDestinationRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateDestinationRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateDestinationRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateDestinationRequest(val *CreateDestinationRequest) *NullableCreateDestinationRequest {
	return &NullableCreateDestinationRequest{value: val, isSet: true}
}

func (v NullableCreateDestinationRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateDestinationRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


