/*
GetHook API

Webhook Reliability Gateway — accept inbound webhooks, persist them durably, forward to destinations, retry failures, and replay past events.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gethook

import (
	"encoding/json"
)

// checks if the ProviderPreset type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProviderPreset{}

// ProviderPreset struct for ProviderPreset
type ProviderPreset struct {
	AuthMode *string `json:"auth_mode,omitempty"`
	Category *string `json:"category,omitempty"`
	Color *string `json:"color,omitempty"`
	Description *string `json:"description,omitempty"`
	DocsUrl *string `json:"docs_url,omitempty"`
	Header *string `json:"header,omitempty"`
	Id *string `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
}

// NewProviderPreset instantiates a new ProviderPreset object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProviderPreset() *ProviderPreset {
	this := ProviderPreset{}
	return &this
}

// NewProviderPresetWithDefaults instantiates a new ProviderPreset object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProviderPresetWithDefaults() *ProviderPreset {
	this := ProviderPreset{}
	return &this
}

// GetAuthMode returns the AuthMode field value if set, zero value otherwise.
func (o *ProviderPreset) GetAuthMode() string {
	if o == nil || IsNil(o.AuthMode) {
		var ret string
		return ret
	}
	return *o.AuthMode
}

// GetAuthModeOk returns a tuple with the AuthMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProviderPreset) GetAuthModeOk() (*string, bool) {
	if o == nil || IsNil(o.AuthMode) {
		return nil, false
	}
	return o.AuthMode, true
}

// HasAuthMode returns a boolean if a field has been set.
func (o *ProviderPreset) HasAuthMode() bool {
	if o != nil && !IsNil(o.AuthMode) {
		return true
	}

	return false
}

// SetAuthMode gets a reference to the given string and assigns it to the AuthMode field.
func (o *ProviderPreset) SetAuthMode(v string) {
	o.AuthMode = &v
}

// GetCategory returns the Category field value if set, zero value otherwise.
func (o *ProviderPreset) GetCategory() string {
	if o == nil || IsNil(o.Category) {
		var ret string
		return ret
	}
	return *o.Category
}

// GetCategoryOk returns a tuple with the Category field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProviderPreset) GetCategoryOk() (*string, bool) {
	if o == nil || IsNil(o.Category) {
		return nil, false
	}
	return o.Category, true
}

// HasCategory returns a boolean if a field has been set.
func (o *ProviderPreset) HasCategory() bool {
	if o != nil && !IsNil(o.Category) {
		return true
	}

	return false
}

// SetCategory gets a reference to the given string and assigns it to the Category field.
func (o *ProviderPreset) SetCategory(v string) {
	o.Category = &v
}

// GetColor returns the Color field value if set, zero value otherwise.
func (o *ProviderPreset) GetColor() string {
	if o == nil || IsNil(o.Color) {
		var ret string
		return ret
	}
	return *o.Color
}

// GetColorOk returns a tuple with the Color field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProviderPreset) GetColorOk() (*string, bool) {
	if o == nil || IsNil(o.Color) {
		return nil, false
	}
	return o.Color, true
}

// HasColor returns a boolean if a field has been set.
func (o *ProviderPreset) HasColor() bool {
	if o != nil && !IsNil(o.Color) {
		return true
	}

	return false
}

// SetColor gets a reference to the given string and assigns it to the Color field.
func (o *ProviderPreset) SetColor(v string) {
	o.Color = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ProviderPreset) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProviderPreset) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ProviderPreset) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ProviderPreset) SetDescription(v string) {
	o.Description = &v
}

// GetDocsUrl returns the DocsUrl field value if set, zero value otherwise.
func (o *ProviderPreset) GetDocsUrl() string {
	if o == nil || IsNil(o.DocsUrl) {
		var ret string
		return ret
	}
	return *o.DocsUrl
}

// GetDocsUrlOk returns a tuple with the DocsUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProviderPreset) GetDocsUrlOk() (*string, bool) {
	if o == nil || IsNil(o.DocsUrl) {
		return nil, false
	}
	return o.DocsUrl, true
}

// HasDocsUrl returns a boolean if a field has been set.
func (o *ProviderPreset) HasDocsUrl() bool {
	if o != nil && !IsNil(o.DocsUrl) {
		return true
	}

	return false
}

// SetDocsUrl gets a reference to the given string and assigns it to the DocsUrl field.
func (o *ProviderPreset) SetDocsUrl(v string) {
	o.DocsUrl = &v
}

// GetHeader returns the Header field value if set, zero value otherwise.
func (o *ProviderPreset) GetHeader() string {
	if o == nil || IsNil(o.Header) {
		var ret string
		return ret
	}
	return *o.Header
}

// GetHeaderOk returns a tuple with the Header field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProviderPreset) GetHeaderOk() (*string, bool) {
	if o == nil || IsNil(o.Header) {
		return nil, false
	}
	return o.Header, true
}

// HasHeader returns a boolean if a field has been set.
func (o *ProviderPreset) HasHeader() bool {
	if o != nil && !IsNil(o.Header) {
		return true
	}

	return false
}

// SetHeader gets a reference to the given string and assigns it to the Header field.
func (o *ProviderPreset) SetHeader(v string) {
	o.Header = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ProviderPreset) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProviderPreset) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ProviderPreset) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ProviderPreset) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ProviderPreset) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProviderPreset) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ProviderPreset) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ProviderPreset) SetName(v string) {
	o.Name = &v
}

func (o ProviderPreset) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProviderPreset) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AuthMode) {
		toSerialize["auth_mode"] = o.AuthMode
	}
	if !IsNil(o.Category) {
		toSerialize["category"] = o.Category
	}
	if !IsNil(o.Color) {
		toSerialize["color"] = o.Color
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.DocsUrl) {
		toSerialize["docs_url"] = o.DocsUrl
	}
	if !IsNil(o.Header) {
		toSerialize["header"] = o.Header
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return toSerialize, nil
}

type NullableProviderPreset struct {
	value *ProviderPreset
	isSet bool
}

func (v NullableProviderPreset) Get() *ProviderPreset {
	return v.value
}

func (v *NullableProviderPreset) Set(val *ProviderPreset) {
	v.value = val
	v.isSet = true
}

func (v NullableProviderPreset) IsSet() bool {
	return v.isSet
}

func (v *NullableProviderPreset) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProviderPreset(val *ProviderPreset) *NullableProviderPreset {
	return &NullableProviderPreset{value: val, isSet: true}
}

func (v NullableProviderPreset) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProviderPreset) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


