/*
GetHook API

Webhook Reliability Gateway — accept inbound webhooks, persist them durably, forward to destinations, retry failures, and replay past events.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gethook

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Source type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Source{}

// Source struct for Source
type Source struct {
	AccountId string `json:"account_id"`
	AuthMode string `json:"auth_mode"`
	CreatedAt string `json:"created_at"`
	CustomDomainId *string `json:"custom_domain_id,omitempty"`
	Id string `json:"id"`
	IngestUrl string `json:"ingest_url"`
	Name string `json:"name"`
	PathToken string `json:"path_token"`
	Status string `json:"status"`
	VerificationConfig map[string]interface{} `json:"verification_config,omitempty"`
}

type _Source Source

// NewSource instantiates a new Source object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSource(accountId string, authMode string, createdAt string, id string, ingestUrl string, name string, pathToken string, status string) *Source {
	this := Source{}
	this.AccountId = accountId
	this.AuthMode = authMode
	this.CreatedAt = createdAt
	this.Id = id
	this.IngestUrl = ingestUrl
	this.Name = name
	this.PathToken = pathToken
	this.Status = status
	return &this
}

// NewSourceWithDefaults instantiates a new Source object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSourceWithDefaults() *Source {
	this := Source{}
	return &this
}

// GetAccountId returns the AccountId field value
func (o *Source) GetAccountId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value
// and a boolean to check if the value has been set.
func (o *Source) GetAccountIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccountId, true
}

// SetAccountId sets field value
func (o *Source) SetAccountId(v string) {
	o.AccountId = v
}

// GetAuthMode returns the AuthMode field value
func (o *Source) GetAuthMode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AuthMode
}

// GetAuthModeOk returns a tuple with the AuthMode field value
// and a boolean to check if the value has been set.
func (o *Source) GetAuthModeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AuthMode, true
}

// SetAuthMode sets field value
func (o *Source) SetAuthMode(v string) {
	o.AuthMode = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *Source) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *Source) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *Source) SetCreatedAt(v string) {
	o.CreatedAt = v
}

// GetCustomDomainId returns the CustomDomainId field value if set, zero value otherwise.
func (o *Source) GetCustomDomainId() string {
	if o == nil || IsNil(o.CustomDomainId) {
		var ret string
		return ret
	}
	return *o.CustomDomainId
}

// GetCustomDomainIdOk returns a tuple with the CustomDomainId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Source) GetCustomDomainIdOk() (*string, bool) {
	if o == nil || IsNil(o.CustomDomainId) {
		return nil, false
	}
	return o.CustomDomainId, true
}

// HasCustomDomainId returns a boolean if a field has been set.
func (o *Source) HasCustomDomainId() bool {
	if o != nil && !IsNil(o.CustomDomainId) {
		return true
	}

	return false
}

// SetCustomDomainId gets a reference to the given string and assigns it to the CustomDomainId field.
func (o *Source) SetCustomDomainId(v string) {
	o.CustomDomainId = &v
}

// GetId returns the Id field value
func (o *Source) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *Source) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *Source) SetId(v string) {
	o.Id = v
}

// GetIngestUrl returns the IngestUrl field value
func (o *Source) GetIngestUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IngestUrl
}

// GetIngestUrlOk returns a tuple with the IngestUrl field value
// and a boolean to check if the value has been set.
func (o *Source) GetIngestUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IngestUrl, true
}

// SetIngestUrl sets field value
func (o *Source) SetIngestUrl(v string) {
	o.IngestUrl = v
}

// GetName returns the Name field value
func (o *Source) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *Source) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *Source) SetName(v string) {
	o.Name = v
}

// GetPathToken returns the PathToken field value
func (o *Source) GetPathToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PathToken
}

// GetPathTokenOk returns a tuple with the PathToken field value
// and a boolean to check if the value has been set.
func (o *Source) GetPathTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PathToken, true
}

// SetPathToken sets field value
func (o *Source) SetPathToken(v string) {
	o.PathToken = v
}

// GetStatus returns the Status field value
func (o *Source) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *Source) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *Source) SetStatus(v string) {
	o.Status = v
}

// GetVerificationConfig returns the VerificationConfig field value if set, zero value otherwise.
func (o *Source) GetVerificationConfig() map[string]interface{} {
	if o == nil || IsNil(o.VerificationConfig) {
		var ret map[string]interface{}
		return ret
	}
	return o.VerificationConfig
}

// GetVerificationConfigOk returns a tuple with the VerificationConfig field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Source) GetVerificationConfigOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.VerificationConfig) {
		return map[string]interface{}{}, false
	}
	return o.VerificationConfig, true
}

// HasVerificationConfig returns a boolean if a field has been set.
func (o *Source) HasVerificationConfig() bool {
	if o != nil && !IsNil(o.VerificationConfig) {
		return true
	}

	return false
}

// SetVerificationConfig gets a reference to the given map[string]interface{} and assigns it to the VerificationConfig field.
func (o *Source) SetVerificationConfig(v map[string]interface{}) {
	o.VerificationConfig = v
}

func (o Source) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Source) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["account_id"] = o.AccountId
	toSerialize["auth_mode"] = o.AuthMode
	toSerialize["created_at"] = o.CreatedAt
	if !IsNil(o.CustomDomainId) {
		toSerialize["custom_domain_id"] = o.CustomDomainId
	}
	toSerialize["id"] = o.Id
	toSerialize["ingest_url"] = o.IngestUrl
	toSerialize["name"] = o.Name
	toSerialize["path_token"] = o.PathToken
	toSerialize["status"] = o.Status
	if !IsNil(o.VerificationConfig) {
		toSerialize["verification_config"] = o.VerificationConfig
	}
	return toSerialize, nil
}

func (o *Source) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"account_id",
		"auth_mode",
		"created_at",
		"id",
		"ingest_url",
		"name",
		"path_token",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSource := _Source{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSource)

	if err != nil {
		return err
	}

	*o = Source(varSource)

	return err
}

type NullableSource struct {
	value *Source
	isSet bool
}

func (v NullableSource) Get() *Source {
	return v.value
}

func (v *NullableSource) Set(val *Source) {
	v.value = val
	v.isSet = true
}

func (v NullableSource) IsSet() bool {
	return v.isSet
}

func (v *NullableSource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSource(val *Source) *NullableSource {
	return &NullableSource{value: val, isSet: true}
}

func (v NullableSource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


