/*
GetHook API

Webhook Reliability Gateway — accept inbound webhooks, persist them durably, forward to destinations, retry failures, and replay past events.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gethook

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DeliveryAttempt type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeliveryAttempt{}

// DeliveryAttempt struct for DeliveryAttempt
type DeliveryAttempt struct {
	AttemptNumber int32 `json:"attempt_number"`
	DestinationId string `json:"destination_id"`
	ErrorMessage *string `json:"error_message,omitempty"`
	EventId string `json:"event_id"`
	FinishedAt *string `json:"finished_at,omitempty"`
	Id string `json:"id"`
	LatencyMs *int32 `json:"latency_ms,omitempty"`
	Outcome AttemptOutcome `json:"outcome"`
	ResponseBody *string `json:"response_body,omitempty"`
	ResponseStatus *int32 `json:"response_status,omitempty"`
	StartedAt string `json:"started_at"`
}

type _DeliveryAttempt DeliveryAttempt

// NewDeliveryAttempt instantiates a new DeliveryAttempt object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeliveryAttempt(attemptNumber int32, destinationId string, eventId string, id string, outcome AttemptOutcome, startedAt string) *DeliveryAttempt {
	this := DeliveryAttempt{}
	this.AttemptNumber = attemptNumber
	this.DestinationId = destinationId
	this.EventId = eventId
	this.Id = id
	this.Outcome = outcome
	this.StartedAt = startedAt
	return &this
}

// NewDeliveryAttemptWithDefaults instantiates a new DeliveryAttempt object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeliveryAttemptWithDefaults() *DeliveryAttempt {
	this := DeliveryAttempt{}
	return &this
}

// GetAttemptNumber returns the AttemptNumber field value
func (o *DeliveryAttempt) GetAttemptNumber() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.AttemptNumber
}

// GetAttemptNumberOk returns a tuple with the AttemptNumber field value
// and a boolean to check if the value has been set.
func (o *DeliveryAttempt) GetAttemptNumberOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AttemptNumber, true
}

// SetAttemptNumber sets field value
func (o *DeliveryAttempt) SetAttemptNumber(v int32) {
	o.AttemptNumber = v
}

// GetDestinationId returns the DestinationId field value
func (o *DeliveryAttempt) GetDestinationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DestinationId
}

// GetDestinationIdOk returns a tuple with the DestinationId field value
// and a boolean to check if the value has been set.
func (o *DeliveryAttempt) GetDestinationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DestinationId, true
}

// SetDestinationId sets field value
func (o *DeliveryAttempt) SetDestinationId(v string) {
	o.DestinationId = v
}

// GetErrorMessage returns the ErrorMessage field value if set, zero value otherwise.
func (o *DeliveryAttempt) GetErrorMessage() string {
	if o == nil || IsNil(o.ErrorMessage) {
		var ret string
		return ret
	}
	return *o.ErrorMessage
}

// GetErrorMessageOk returns a tuple with the ErrorMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeliveryAttempt) GetErrorMessageOk() (*string, bool) {
	if o == nil || IsNil(o.ErrorMessage) {
		return nil, false
	}
	return o.ErrorMessage, true
}

// HasErrorMessage returns a boolean if a field has been set.
func (o *DeliveryAttempt) HasErrorMessage() bool {
	if o != nil && !IsNil(o.ErrorMessage) {
		return true
	}

	return false
}

// SetErrorMessage gets a reference to the given string and assigns it to the ErrorMessage field.
func (o *DeliveryAttempt) SetErrorMessage(v string) {
	o.ErrorMessage = &v
}

// GetEventId returns the EventId field value
func (o *DeliveryAttempt) GetEventId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EventId
}

// GetEventIdOk returns a tuple with the EventId field value
// and a boolean to check if the value has been set.
func (o *DeliveryAttempt) GetEventIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EventId, true
}

// SetEventId sets field value
func (o *DeliveryAttempt) SetEventId(v string) {
	o.EventId = v
}

// GetFinishedAt returns the FinishedAt field value if set, zero value otherwise.
func (o *DeliveryAttempt) GetFinishedAt() string {
	if o == nil || IsNil(o.FinishedAt) {
		var ret string
		return ret
	}
	return *o.FinishedAt
}

// GetFinishedAtOk returns a tuple with the FinishedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeliveryAttempt) GetFinishedAtOk() (*string, bool) {
	if o == nil || IsNil(o.FinishedAt) {
		return nil, false
	}
	return o.FinishedAt, true
}

// HasFinishedAt returns a boolean if a field has been set.
func (o *DeliveryAttempt) HasFinishedAt() bool {
	if o != nil && !IsNil(o.FinishedAt) {
		return true
	}

	return false
}

// SetFinishedAt gets a reference to the given string and assigns it to the FinishedAt field.
func (o *DeliveryAttempt) SetFinishedAt(v string) {
	o.FinishedAt = &v
}

// GetId returns the Id field value
func (o *DeliveryAttempt) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *DeliveryAttempt) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *DeliveryAttempt) SetId(v string) {
	o.Id = v
}

// GetLatencyMs returns the LatencyMs field value if set, zero value otherwise.
func (o *DeliveryAttempt) GetLatencyMs() int32 {
	if o == nil || IsNil(o.LatencyMs) {
		var ret int32
		return ret
	}
	return *o.LatencyMs
}

// GetLatencyMsOk returns a tuple with the LatencyMs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeliveryAttempt) GetLatencyMsOk() (*int32, bool) {
	if o == nil || IsNil(o.LatencyMs) {
		return nil, false
	}
	return o.LatencyMs, true
}

// HasLatencyMs returns a boolean if a field has been set.
func (o *DeliveryAttempt) HasLatencyMs() bool {
	if o != nil && !IsNil(o.LatencyMs) {
		return true
	}

	return false
}

// SetLatencyMs gets a reference to the given int32 and assigns it to the LatencyMs field.
func (o *DeliveryAttempt) SetLatencyMs(v int32) {
	o.LatencyMs = &v
}

// GetOutcome returns the Outcome field value
func (o *DeliveryAttempt) GetOutcome() AttemptOutcome {
	if o == nil {
		var ret AttemptOutcome
		return ret
	}

	return o.Outcome
}

// GetOutcomeOk returns a tuple with the Outcome field value
// and a boolean to check if the value has been set.
func (o *DeliveryAttempt) GetOutcomeOk() (*AttemptOutcome, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Outcome, true
}

// SetOutcome sets field value
func (o *DeliveryAttempt) SetOutcome(v AttemptOutcome) {
	o.Outcome = v
}

// GetResponseBody returns the ResponseBody field value if set, zero value otherwise.
func (o *DeliveryAttempt) GetResponseBody() string {
	if o == nil || IsNil(o.ResponseBody) {
		var ret string
		return ret
	}
	return *o.ResponseBody
}

// GetResponseBodyOk returns a tuple with the ResponseBody field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeliveryAttempt) GetResponseBodyOk() (*string, bool) {
	if o == nil || IsNil(o.ResponseBody) {
		return nil, false
	}
	return o.ResponseBody, true
}

// HasResponseBody returns a boolean if a field has been set.
func (o *DeliveryAttempt) HasResponseBody() bool {
	if o != nil && !IsNil(o.ResponseBody) {
		return true
	}

	return false
}

// SetResponseBody gets a reference to the given string and assigns it to the ResponseBody field.
func (o *DeliveryAttempt) SetResponseBody(v string) {
	o.ResponseBody = &v
}

// GetResponseStatus returns the ResponseStatus field value if set, zero value otherwise.
func (o *DeliveryAttempt) GetResponseStatus() int32 {
	if o == nil || IsNil(o.ResponseStatus) {
		var ret int32
		return ret
	}
	return *o.ResponseStatus
}

// GetResponseStatusOk returns a tuple with the ResponseStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeliveryAttempt) GetResponseStatusOk() (*int32, bool) {
	if o == nil || IsNil(o.ResponseStatus) {
		return nil, false
	}
	return o.ResponseStatus, true
}

// HasResponseStatus returns a boolean if a field has been set.
func (o *DeliveryAttempt) HasResponseStatus() bool {
	if o != nil && !IsNil(o.ResponseStatus) {
		return true
	}

	return false
}

// SetResponseStatus gets a reference to the given int32 and assigns it to the ResponseStatus field.
func (o *DeliveryAttempt) SetResponseStatus(v int32) {
	o.ResponseStatus = &v
}

// GetStartedAt returns the StartedAt field value
func (o *DeliveryAttempt) GetStartedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.StartedAt
}

// GetStartedAtOk returns a tuple with the StartedAt field value
// and a boolean to check if the value has been set.
func (o *DeliveryAttempt) GetStartedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StartedAt, true
}

// SetStartedAt sets field value
func (o *DeliveryAttempt) SetStartedAt(v string) {
	o.StartedAt = v
}

func (o DeliveryAttempt) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeliveryAttempt) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["attempt_number"] = o.AttemptNumber
	toSerialize["destination_id"] = o.DestinationId
	if !IsNil(o.ErrorMessage) {
		toSerialize["error_message"] = o.ErrorMessage
	}
	toSerialize["event_id"] = o.EventId
	if !IsNil(o.FinishedAt) {
		toSerialize["finished_at"] = o.FinishedAt
	}
	toSerialize["id"] = o.Id
	if !IsNil(o.LatencyMs) {
		toSerialize["latency_ms"] = o.LatencyMs
	}
	toSerialize["outcome"] = o.Outcome
	if !IsNil(o.ResponseBody) {
		toSerialize["response_body"] = o.ResponseBody
	}
	if !IsNil(o.ResponseStatus) {
		toSerialize["response_status"] = o.ResponseStatus
	}
	toSerialize["started_at"] = o.StartedAt
	return toSerialize, nil
}

func (o *DeliveryAttempt) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"attempt_number",
		"destination_id",
		"event_id",
		"id",
		"outcome",
		"started_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeliveryAttempt := _DeliveryAttempt{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDeliveryAttempt)

	if err != nil {
		return err
	}

	*o = DeliveryAttempt(varDeliveryAttempt)

	return err
}

type NullableDeliveryAttempt struct {
	value *DeliveryAttempt
	isSet bool
}

func (v NullableDeliveryAttempt) Get() *DeliveryAttempt {
	return v.value
}

func (v *NullableDeliveryAttempt) Set(val *DeliveryAttempt) {
	v.value = val
	v.isSet = true
}

func (v NullableDeliveryAttempt) IsSet() bool {
	return v.isSet
}

func (v *NullableDeliveryAttempt) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeliveryAttempt(val *DeliveryAttempt) *NullableDeliveryAttempt {
	return &NullableDeliveryAttempt{value: val, isSet: true}
}

func (v NullableDeliveryAttempt) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeliveryAttempt) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


