/*
GetHook API

Webhook Reliability Gateway — accept inbound webhooks, persist them durably, forward to destinations, retry failures, and replay past events.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gethook

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ReplayEventData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ReplayEventData{}

// ReplayEventData struct for ReplayEventData
type ReplayEventData struct {
	OriginalEventId string `json:"original_event_id"`
	ReplayEventId string `json:"replay_event_id"`
	Status string `json:"status"`
}

type _ReplayEventData ReplayEventData

// NewReplayEventData instantiates a new ReplayEventData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReplayEventData(originalEventId string, replayEventId string, status string) *ReplayEventData {
	this := ReplayEventData{}
	this.OriginalEventId = originalEventId
	this.ReplayEventId = replayEventId
	this.Status = status
	return &this
}

// NewReplayEventDataWithDefaults instantiates a new ReplayEventData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReplayEventDataWithDefaults() *ReplayEventData {
	this := ReplayEventData{}
	return &this
}

// GetOriginalEventId returns the OriginalEventId field value
func (o *ReplayEventData) GetOriginalEventId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OriginalEventId
}

// GetOriginalEventIdOk returns a tuple with the OriginalEventId field value
// and a boolean to check if the value has been set.
func (o *ReplayEventData) GetOriginalEventIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OriginalEventId, true
}

// SetOriginalEventId sets field value
func (o *ReplayEventData) SetOriginalEventId(v string) {
	o.OriginalEventId = v
}

// GetReplayEventId returns the ReplayEventId field value
func (o *ReplayEventData) GetReplayEventId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ReplayEventId
}

// GetReplayEventIdOk returns a tuple with the ReplayEventId field value
// and a boolean to check if the value has been set.
func (o *ReplayEventData) GetReplayEventIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReplayEventId, true
}

// SetReplayEventId sets field value
func (o *ReplayEventData) SetReplayEventId(v string) {
	o.ReplayEventId = v
}

// GetStatus returns the Status field value
func (o *ReplayEventData) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *ReplayEventData) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *ReplayEventData) SetStatus(v string) {
	o.Status = v
}

func (o ReplayEventData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ReplayEventData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["original_event_id"] = o.OriginalEventId
	toSerialize["replay_event_id"] = o.ReplayEventId
	toSerialize["status"] = o.Status
	return toSerialize, nil
}

func (o *ReplayEventData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"original_event_id",
		"replay_event_id",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varReplayEventData := _ReplayEventData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varReplayEventData)

	if err != nil {
		return err
	}

	*o = ReplayEventData(varReplayEventData)

	return err
}

type NullableReplayEventData struct {
	value *ReplayEventData
	isSet bool
}

func (v NullableReplayEventData) Get() *ReplayEventData {
	return v.value
}

func (v *NullableReplayEventData) Set(val *ReplayEventData) {
	v.value = val
	v.isSet = true
}

func (v NullableReplayEventData) IsSet() bool {
	return v.isSet
}

func (v *NullableReplayEventData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReplayEventData(val *ReplayEventData) *NullableReplayEventData {
	return &NullableReplayEventData{value: val, isSet: true}
}

func (v NullableReplayEventData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReplayEventData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


