/*
GetHook API

Webhook Reliability Gateway — accept inbound webhooks, persist them durably, forward to destinations, retry failures, and replay past events.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gethook

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the StatsDailyItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StatsDailyItem{}

// StatsDailyItem struct for StatsDailyItem
type StatsDailyItem struct {
	Date string `json:"date"`
	Delivered int32 `json:"delivered"`
	Failed int32 `json:"failed"`
	Inbound int32 `json:"inbound"`
	Outbound int32 `json:"outbound"`
}

type _StatsDailyItem StatsDailyItem

// NewStatsDailyItem instantiates a new StatsDailyItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStatsDailyItem(date string, delivered int32, failed int32, inbound int32, outbound int32) *StatsDailyItem {
	this := StatsDailyItem{}
	this.Date = date
	this.Delivered = delivered
	this.Failed = failed
	this.Inbound = inbound
	this.Outbound = outbound
	return &this
}

// NewStatsDailyItemWithDefaults instantiates a new StatsDailyItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStatsDailyItemWithDefaults() *StatsDailyItem {
	this := StatsDailyItem{}
	return &this
}

// GetDate returns the Date field value
func (o *StatsDailyItem) GetDate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Date
}

// GetDateOk returns a tuple with the Date field value
// and a boolean to check if the value has been set.
func (o *StatsDailyItem) GetDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Date, true
}

// SetDate sets field value
func (o *StatsDailyItem) SetDate(v string) {
	o.Date = v
}

// GetDelivered returns the Delivered field value
func (o *StatsDailyItem) GetDelivered() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Delivered
}

// GetDeliveredOk returns a tuple with the Delivered field value
// and a boolean to check if the value has been set.
func (o *StatsDailyItem) GetDeliveredOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Delivered, true
}

// SetDelivered sets field value
func (o *StatsDailyItem) SetDelivered(v int32) {
	o.Delivered = v
}

// GetFailed returns the Failed field value
func (o *StatsDailyItem) GetFailed() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Failed
}

// GetFailedOk returns a tuple with the Failed field value
// and a boolean to check if the value has been set.
func (o *StatsDailyItem) GetFailedOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Failed, true
}

// SetFailed sets field value
func (o *StatsDailyItem) SetFailed(v int32) {
	o.Failed = v
}

// GetInbound returns the Inbound field value
func (o *StatsDailyItem) GetInbound() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Inbound
}

// GetInboundOk returns a tuple with the Inbound field value
// and a boolean to check if the value has been set.
func (o *StatsDailyItem) GetInboundOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Inbound, true
}

// SetInbound sets field value
func (o *StatsDailyItem) SetInbound(v int32) {
	o.Inbound = v
}

// GetOutbound returns the Outbound field value
func (o *StatsDailyItem) GetOutbound() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Outbound
}

// GetOutboundOk returns a tuple with the Outbound field value
// and a boolean to check if the value has been set.
func (o *StatsDailyItem) GetOutboundOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Outbound, true
}

// SetOutbound sets field value
func (o *StatsDailyItem) SetOutbound(v int32) {
	o.Outbound = v
}

func (o StatsDailyItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StatsDailyItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["date"] = o.Date
	toSerialize["delivered"] = o.Delivered
	toSerialize["failed"] = o.Failed
	toSerialize["inbound"] = o.Inbound
	toSerialize["outbound"] = o.Outbound
	return toSerialize, nil
}

func (o *StatsDailyItem) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"date",
		"delivered",
		"failed",
		"inbound",
		"outbound",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varStatsDailyItem := _StatsDailyItem{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varStatsDailyItem)

	if err != nil {
		return err
	}

	*o = StatsDailyItem(varStatsDailyItem)

	return err
}

type NullableStatsDailyItem struct {
	value *StatsDailyItem
	isSet bool
}

func (v NullableStatsDailyItem) Get() *StatsDailyItem {
	return v.value
}

func (v *NullableStatsDailyItem) Set(val *StatsDailyItem) {
	v.value = val
	v.isSet = true
}

func (v NullableStatsDailyItem) IsSet() bool {
	return v.isSet
}

func (v *NullableStatsDailyItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStatsDailyItem(val *StatsDailyItem) *NullableStatsDailyItem {
	return &NullableStatsDailyItem{value: val, isSet: true}
}

func (v NullableStatsDailyItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStatsDailyItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


