/*
GetHook API

Webhook Reliability Gateway — accept inbound webhooks, persist them durably, forward to destinations, retry failures, and replay past events.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gethook

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateRouteRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateRouteRequest{}

// CreateRouteRequest struct for CreateRouteRequest
type CreateRouteRequest struct {
	DestinationId string `json:"destination_id"`
	EventTypePattern *string `json:"event_type_pattern,omitempty"`
	SourceId *string `json:"source_id,omitempty"`
}

type _CreateRouteRequest CreateRouteRequest

// NewCreateRouteRequest instantiates a new CreateRouteRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateRouteRequest(destinationId string) *CreateRouteRequest {
	this := CreateRouteRequest{}
	this.DestinationId = destinationId
	return &this
}

// NewCreateRouteRequestWithDefaults instantiates a new CreateRouteRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateRouteRequestWithDefaults() *CreateRouteRequest {
	this := CreateRouteRequest{}
	return &this
}

// GetDestinationId returns the DestinationId field value
func (o *CreateRouteRequest) GetDestinationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DestinationId
}

// GetDestinationIdOk returns a tuple with the DestinationId field value
// and a boolean to check if the value has been set.
func (o *CreateRouteRequest) GetDestinationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DestinationId, true
}

// SetDestinationId sets field value
func (o *CreateRouteRequest) SetDestinationId(v string) {
	o.DestinationId = v
}

// GetEventTypePattern returns the EventTypePattern field value if set, zero value otherwise.
func (o *CreateRouteRequest) GetEventTypePattern() string {
	if o == nil || IsNil(o.EventTypePattern) {
		var ret string
		return ret
	}
	return *o.EventTypePattern
}

// GetEventTypePatternOk returns a tuple with the EventTypePattern field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateRouteRequest) GetEventTypePatternOk() (*string, bool) {
	if o == nil || IsNil(o.EventTypePattern) {
		return nil, false
	}
	return o.EventTypePattern, true
}

// HasEventTypePattern returns a boolean if a field has been set.
func (o *CreateRouteRequest) HasEventTypePattern() bool {
	if o != nil && !IsNil(o.EventTypePattern) {
		return true
	}

	return false
}

// SetEventTypePattern gets a reference to the given string and assigns it to the EventTypePattern field.
func (o *CreateRouteRequest) SetEventTypePattern(v string) {
	o.EventTypePattern = &v
}

// GetSourceId returns the SourceId field value if set, zero value otherwise.
func (o *CreateRouteRequest) GetSourceId() string {
	if o == nil || IsNil(o.SourceId) {
		var ret string
		return ret
	}
	return *o.SourceId
}

// GetSourceIdOk returns a tuple with the SourceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateRouteRequest) GetSourceIdOk() (*string, bool) {
	if o == nil || IsNil(o.SourceId) {
		return nil, false
	}
	return o.SourceId, true
}

// HasSourceId returns a boolean if a field has been set.
func (o *CreateRouteRequest) HasSourceId() bool {
	if o != nil && !IsNil(o.SourceId) {
		return true
	}

	return false
}

// SetSourceId gets a reference to the given string and assigns it to the SourceId field.
func (o *CreateRouteRequest) SetSourceId(v string) {
	o.SourceId = &v
}

func (o CreateRouteRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateRouteRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["destination_id"] = o.DestinationId
	if !IsNil(o.EventTypePattern) {
		toSerialize["event_type_pattern"] = o.EventTypePattern
	}
	if !IsNil(o.SourceId) {
		toSerialize["source_id"] = o.SourceId
	}
	return toSerialize, nil
}

func (o *CreateRouteRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"destination_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateRouteRequest := _CreateRouteRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateRouteRequest)

	if err != nil {
		return err
	}

	*o = CreateRouteRequest(varCreateRouteRequest)

	return err
}

type NullableCreateRouteRequest struct {
	value *CreateRouteRequest
	isSet bool
}

func (v NullableCreateRouteRequest) Get() *CreateRouteRequest {
	return v.value
}

func (v *NullableCreateRouteRequest) Set(val *CreateRouteRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateRouteRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateRouteRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateRouteRequest(val *CreateRouteRequest) *NullableCreateRouteRequest {
	return &NullableCreateRouteRequest{value: val, isSet: true}
}

func (v NullableCreateRouteRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateRouteRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


