/*
GetHook API

Webhook Reliability Gateway — accept inbound webhooks, persist them durably, forward to destinations, retry failures, and replay past events.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gethook

import (
	"encoding/json"
)

// checks if the DestinationPreset type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DestinationPreset{}

// DestinationPreset struct for DestinationPreset
type DestinationPreset struct {
	// for api_key type
	AuthHeader *string `json:"auth_header,omitempty"`
	// e.g. \"Bot Token\", \"API Key\"
	AuthLabel *string `json:"auth_label,omitempty"`
	// \"none\", \"bearer\", \"api_key\"
	AuthType *string `json:"auth_type,omitempty"`
	Category *string `json:"category,omitempty"`
	Color *string `json:"color,omitempty"`
	Description *string `json:"description,omitempty"`
	DocsUrl *string `json:"docs_url,omitempty"`
	ExtraHeaders *map[string]string `json:"extra_headers,omitempty"`
	Id *string `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
	UrlHint *string `json:"url_hint,omitempty"`
}

// NewDestinationPreset instantiates a new DestinationPreset object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDestinationPreset() *DestinationPreset {
	this := DestinationPreset{}
	return &this
}

// NewDestinationPresetWithDefaults instantiates a new DestinationPreset object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDestinationPresetWithDefaults() *DestinationPreset {
	this := DestinationPreset{}
	return &this
}

// GetAuthHeader returns the AuthHeader field value if set, zero value otherwise.
func (o *DestinationPreset) GetAuthHeader() string {
	if o == nil || IsNil(o.AuthHeader) {
		var ret string
		return ret
	}
	return *o.AuthHeader
}

// GetAuthHeaderOk returns a tuple with the AuthHeader field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DestinationPreset) GetAuthHeaderOk() (*string, bool) {
	if o == nil || IsNil(o.AuthHeader) {
		return nil, false
	}
	return o.AuthHeader, true
}

// HasAuthHeader returns a boolean if a field has been set.
func (o *DestinationPreset) HasAuthHeader() bool {
	if o != nil && !IsNil(o.AuthHeader) {
		return true
	}

	return false
}

// SetAuthHeader gets a reference to the given string and assigns it to the AuthHeader field.
func (o *DestinationPreset) SetAuthHeader(v string) {
	o.AuthHeader = &v
}

// GetAuthLabel returns the AuthLabel field value if set, zero value otherwise.
func (o *DestinationPreset) GetAuthLabel() string {
	if o == nil || IsNil(o.AuthLabel) {
		var ret string
		return ret
	}
	return *o.AuthLabel
}

// GetAuthLabelOk returns a tuple with the AuthLabel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DestinationPreset) GetAuthLabelOk() (*string, bool) {
	if o == nil || IsNil(o.AuthLabel) {
		return nil, false
	}
	return o.AuthLabel, true
}

// HasAuthLabel returns a boolean if a field has been set.
func (o *DestinationPreset) HasAuthLabel() bool {
	if o != nil && !IsNil(o.AuthLabel) {
		return true
	}

	return false
}

// SetAuthLabel gets a reference to the given string and assigns it to the AuthLabel field.
func (o *DestinationPreset) SetAuthLabel(v string) {
	o.AuthLabel = &v
}

// GetAuthType returns the AuthType field value if set, zero value otherwise.
func (o *DestinationPreset) GetAuthType() string {
	if o == nil || IsNil(o.AuthType) {
		var ret string
		return ret
	}
	return *o.AuthType
}

// GetAuthTypeOk returns a tuple with the AuthType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DestinationPreset) GetAuthTypeOk() (*string, bool) {
	if o == nil || IsNil(o.AuthType) {
		return nil, false
	}
	return o.AuthType, true
}

// HasAuthType returns a boolean if a field has been set.
func (o *DestinationPreset) HasAuthType() bool {
	if o != nil && !IsNil(o.AuthType) {
		return true
	}

	return false
}

// SetAuthType gets a reference to the given string and assigns it to the AuthType field.
func (o *DestinationPreset) SetAuthType(v string) {
	o.AuthType = &v
}

// GetCategory returns the Category field value if set, zero value otherwise.
func (o *DestinationPreset) GetCategory() string {
	if o == nil || IsNil(o.Category) {
		var ret string
		return ret
	}
	return *o.Category
}

// GetCategoryOk returns a tuple with the Category field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DestinationPreset) GetCategoryOk() (*string, bool) {
	if o == nil || IsNil(o.Category) {
		return nil, false
	}
	return o.Category, true
}

// HasCategory returns a boolean if a field has been set.
func (o *DestinationPreset) HasCategory() bool {
	if o != nil && !IsNil(o.Category) {
		return true
	}

	return false
}

// SetCategory gets a reference to the given string and assigns it to the Category field.
func (o *DestinationPreset) SetCategory(v string) {
	o.Category = &v
}

// GetColor returns the Color field value if set, zero value otherwise.
func (o *DestinationPreset) GetColor() string {
	if o == nil || IsNil(o.Color) {
		var ret string
		return ret
	}
	return *o.Color
}

// GetColorOk returns a tuple with the Color field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DestinationPreset) GetColorOk() (*string, bool) {
	if o == nil || IsNil(o.Color) {
		return nil, false
	}
	return o.Color, true
}

// HasColor returns a boolean if a field has been set.
func (o *DestinationPreset) HasColor() bool {
	if o != nil && !IsNil(o.Color) {
		return true
	}

	return false
}

// SetColor gets a reference to the given string and assigns it to the Color field.
func (o *DestinationPreset) SetColor(v string) {
	o.Color = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *DestinationPreset) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DestinationPreset) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *DestinationPreset) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *DestinationPreset) SetDescription(v string) {
	o.Description = &v
}

// GetDocsUrl returns the DocsUrl field value if set, zero value otherwise.
func (o *DestinationPreset) GetDocsUrl() string {
	if o == nil || IsNil(o.DocsUrl) {
		var ret string
		return ret
	}
	return *o.DocsUrl
}

// GetDocsUrlOk returns a tuple with the DocsUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DestinationPreset) GetDocsUrlOk() (*string, bool) {
	if o == nil || IsNil(o.DocsUrl) {
		return nil, false
	}
	return o.DocsUrl, true
}

// HasDocsUrl returns a boolean if a field has been set.
func (o *DestinationPreset) HasDocsUrl() bool {
	if o != nil && !IsNil(o.DocsUrl) {
		return true
	}

	return false
}

// SetDocsUrl gets a reference to the given string and assigns it to the DocsUrl field.
func (o *DestinationPreset) SetDocsUrl(v string) {
	o.DocsUrl = &v
}

// GetExtraHeaders returns the ExtraHeaders field value if set, zero value otherwise.
func (o *DestinationPreset) GetExtraHeaders() map[string]string {
	if o == nil || IsNil(o.ExtraHeaders) {
		var ret map[string]string
		return ret
	}
	return *o.ExtraHeaders
}

// GetExtraHeadersOk returns a tuple with the ExtraHeaders field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DestinationPreset) GetExtraHeadersOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.ExtraHeaders) {
		return nil, false
	}
	return o.ExtraHeaders, true
}

// HasExtraHeaders returns a boolean if a field has been set.
func (o *DestinationPreset) HasExtraHeaders() bool {
	if o != nil && !IsNil(o.ExtraHeaders) {
		return true
	}

	return false
}

// SetExtraHeaders gets a reference to the given map[string]string and assigns it to the ExtraHeaders field.
func (o *DestinationPreset) SetExtraHeaders(v map[string]string) {
	o.ExtraHeaders = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *DestinationPreset) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DestinationPreset) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *DestinationPreset) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *DestinationPreset) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *DestinationPreset) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DestinationPreset) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *DestinationPreset) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *DestinationPreset) SetName(v string) {
	o.Name = &v
}

// GetUrlHint returns the UrlHint field value if set, zero value otherwise.
func (o *DestinationPreset) GetUrlHint() string {
	if o == nil || IsNil(o.UrlHint) {
		var ret string
		return ret
	}
	return *o.UrlHint
}

// GetUrlHintOk returns a tuple with the UrlHint field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DestinationPreset) GetUrlHintOk() (*string, bool) {
	if o == nil || IsNil(o.UrlHint) {
		return nil, false
	}
	return o.UrlHint, true
}

// HasUrlHint returns a boolean if a field has been set.
func (o *DestinationPreset) HasUrlHint() bool {
	if o != nil && !IsNil(o.UrlHint) {
		return true
	}

	return false
}

// SetUrlHint gets a reference to the given string and assigns it to the UrlHint field.
func (o *DestinationPreset) SetUrlHint(v string) {
	o.UrlHint = &v
}

func (o DestinationPreset) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DestinationPreset) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AuthHeader) {
		toSerialize["auth_header"] = o.AuthHeader
	}
	if !IsNil(o.AuthLabel) {
		toSerialize["auth_label"] = o.AuthLabel
	}
	if !IsNil(o.AuthType) {
		toSerialize["auth_type"] = o.AuthType
	}
	if !IsNil(o.Category) {
		toSerialize["category"] = o.Category
	}
	if !IsNil(o.Color) {
		toSerialize["color"] = o.Color
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.DocsUrl) {
		toSerialize["docs_url"] = o.DocsUrl
	}
	if !IsNil(o.ExtraHeaders) {
		toSerialize["extra_headers"] = o.ExtraHeaders
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.UrlHint) {
		toSerialize["url_hint"] = o.UrlHint
	}
	return toSerialize, nil
}

type NullableDestinationPreset struct {
	value *DestinationPreset
	isSet bool
}

func (v NullableDestinationPreset) Get() *DestinationPreset {
	return v.value
}

func (v *NullableDestinationPreset) Set(val *DestinationPreset) {
	v.value = val
	v.isSet = true
}

func (v NullableDestinationPreset) IsSet() bool {
	return v.isSet
}

func (v *NullableDestinationPreset) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDestinationPreset(val *DestinationPreset) *NullableDestinationPreset {
	return &NullableDestinationPreset{value: val, isSet: true}
}

func (v NullableDestinationPreset) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDestinationPreset) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


