/*
GetHook API

Webhook Reliability Gateway — accept inbound webhooks, persist them durably, forward to destinations, retry failures, and replay past events.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gethook

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Event type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Event{}

// Event struct for Event
type Event struct {
	AccountId string `json:"account_id"`
	AttemptsCount int32 `json:"attempts_count"`
	Body string `json:"body"`
	CreatedAt string `json:"created_at"`
	CreatedBy *string `json:"created_by,omitempty"`
	Direction Direction `json:"direction"`
	EventType *string `json:"event_type,omitempty"`
	ExternalEventId *string `json:"external_event_id,omitempty"`
	FinalState *string `json:"final_state,omitempty"`
	Headers map[string]interface{} `json:"headers"`
	Id string `json:"id"`
	NextAttemptAt *string `json:"next_attempt_at,omitempty"`
	PayloadHash *string `json:"payload_hash,omitempty"`
	ReceivedAt string `json:"received_at"`
	SourceId *string `json:"source_id,omitempty"`
	Status EventStatus `json:"status"`
}

type _Event Event

// NewEvent instantiates a new Event object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEvent(accountId string, attemptsCount int32, body string, createdAt string, direction Direction, headers map[string]interface{}, id string, receivedAt string, status EventStatus) *Event {
	this := Event{}
	this.AccountId = accountId
	this.AttemptsCount = attemptsCount
	this.Body = body
	this.CreatedAt = createdAt
	this.Direction = direction
	this.Headers = headers
	this.Id = id
	this.ReceivedAt = receivedAt
	this.Status = status
	return &this
}

// NewEventWithDefaults instantiates a new Event object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEventWithDefaults() *Event {
	this := Event{}
	return &this
}

// GetAccountId returns the AccountId field value
func (o *Event) GetAccountId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value
// and a boolean to check if the value has been set.
func (o *Event) GetAccountIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccountId, true
}

// SetAccountId sets field value
func (o *Event) SetAccountId(v string) {
	o.AccountId = v
}

// GetAttemptsCount returns the AttemptsCount field value
func (o *Event) GetAttemptsCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.AttemptsCount
}

// GetAttemptsCountOk returns a tuple with the AttemptsCount field value
// and a boolean to check if the value has been set.
func (o *Event) GetAttemptsCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AttemptsCount, true
}

// SetAttemptsCount sets field value
func (o *Event) SetAttemptsCount(v int32) {
	o.AttemptsCount = v
}

// GetBody returns the Body field value
func (o *Event) GetBody() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Body
}

// GetBodyOk returns a tuple with the Body field value
// and a boolean to check if the value has been set.
func (o *Event) GetBodyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Body, true
}

// SetBody sets field value
func (o *Event) SetBody(v string) {
	o.Body = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *Event) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *Event) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *Event) SetCreatedAt(v string) {
	o.CreatedAt = v
}

// GetCreatedBy returns the CreatedBy field value if set, zero value otherwise.
func (o *Event) GetCreatedBy() string {
	if o == nil || IsNil(o.CreatedBy) {
		var ret string
		return ret
	}
	return *o.CreatedBy
}

// GetCreatedByOk returns a tuple with the CreatedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetCreatedByOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedBy) {
		return nil, false
	}
	return o.CreatedBy, true
}

// HasCreatedBy returns a boolean if a field has been set.
func (o *Event) HasCreatedBy() bool {
	if o != nil && !IsNil(o.CreatedBy) {
		return true
	}

	return false
}

// SetCreatedBy gets a reference to the given string and assigns it to the CreatedBy field.
func (o *Event) SetCreatedBy(v string) {
	o.CreatedBy = &v
}

// GetDirection returns the Direction field value
func (o *Event) GetDirection() Direction {
	if o == nil {
		var ret Direction
		return ret
	}

	return o.Direction
}

// GetDirectionOk returns a tuple with the Direction field value
// and a boolean to check if the value has been set.
func (o *Event) GetDirectionOk() (*Direction, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Direction, true
}

// SetDirection sets field value
func (o *Event) SetDirection(v Direction) {
	o.Direction = v
}

// GetEventType returns the EventType field value if set, zero value otherwise.
func (o *Event) GetEventType() string {
	if o == nil || IsNil(o.EventType) {
		var ret string
		return ret
	}
	return *o.EventType
}

// GetEventTypeOk returns a tuple with the EventType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetEventTypeOk() (*string, bool) {
	if o == nil || IsNil(o.EventType) {
		return nil, false
	}
	return o.EventType, true
}

// HasEventType returns a boolean if a field has been set.
func (o *Event) HasEventType() bool {
	if o != nil && !IsNil(o.EventType) {
		return true
	}

	return false
}

// SetEventType gets a reference to the given string and assigns it to the EventType field.
func (o *Event) SetEventType(v string) {
	o.EventType = &v
}

// GetExternalEventId returns the ExternalEventId field value if set, zero value otherwise.
func (o *Event) GetExternalEventId() string {
	if o == nil || IsNil(o.ExternalEventId) {
		var ret string
		return ret
	}
	return *o.ExternalEventId
}

// GetExternalEventIdOk returns a tuple with the ExternalEventId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetExternalEventIdOk() (*string, bool) {
	if o == nil || IsNil(o.ExternalEventId) {
		return nil, false
	}
	return o.ExternalEventId, true
}

// HasExternalEventId returns a boolean if a field has been set.
func (o *Event) HasExternalEventId() bool {
	if o != nil && !IsNil(o.ExternalEventId) {
		return true
	}

	return false
}

// SetExternalEventId gets a reference to the given string and assigns it to the ExternalEventId field.
func (o *Event) SetExternalEventId(v string) {
	o.ExternalEventId = &v
}

// GetFinalState returns the FinalState field value if set, zero value otherwise.
func (o *Event) GetFinalState() string {
	if o == nil || IsNil(o.FinalState) {
		var ret string
		return ret
	}
	return *o.FinalState
}

// GetFinalStateOk returns a tuple with the FinalState field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetFinalStateOk() (*string, bool) {
	if o == nil || IsNil(o.FinalState) {
		return nil, false
	}
	return o.FinalState, true
}

// HasFinalState returns a boolean if a field has been set.
func (o *Event) HasFinalState() bool {
	if o != nil && !IsNil(o.FinalState) {
		return true
	}

	return false
}

// SetFinalState gets a reference to the given string and assigns it to the FinalState field.
func (o *Event) SetFinalState(v string) {
	o.FinalState = &v
}

// GetHeaders returns the Headers field value
func (o *Event) GetHeaders() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Headers
}

// GetHeadersOk returns a tuple with the Headers field value
// and a boolean to check if the value has been set.
func (o *Event) GetHeadersOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Headers, true
}

// SetHeaders sets field value
func (o *Event) SetHeaders(v map[string]interface{}) {
	o.Headers = v
}

// GetId returns the Id field value
func (o *Event) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *Event) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *Event) SetId(v string) {
	o.Id = v
}

// GetNextAttemptAt returns the NextAttemptAt field value if set, zero value otherwise.
func (o *Event) GetNextAttemptAt() string {
	if o == nil || IsNil(o.NextAttemptAt) {
		var ret string
		return ret
	}
	return *o.NextAttemptAt
}

// GetNextAttemptAtOk returns a tuple with the NextAttemptAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetNextAttemptAtOk() (*string, bool) {
	if o == nil || IsNil(o.NextAttemptAt) {
		return nil, false
	}
	return o.NextAttemptAt, true
}

// HasNextAttemptAt returns a boolean if a field has been set.
func (o *Event) HasNextAttemptAt() bool {
	if o != nil && !IsNil(o.NextAttemptAt) {
		return true
	}

	return false
}

// SetNextAttemptAt gets a reference to the given string and assigns it to the NextAttemptAt field.
func (o *Event) SetNextAttemptAt(v string) {
	o.NextAttemptAt = &v
}

// GetPayloadHash returns the PayloadHash field value if set, zero value otherwise.
func (o *Event) GetPayloadHash() string {
	if o == nil || IsNil(o.PayloadHash) {
		var ret string
		return ret
	}
	return *o.PayloadHash
}

// GetPayloadHashOk returns a tuple with the PayloadHash field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetPayloadHashOk() (*string, bool) {
	if o == nil || IsNil(o.PayloadHash) {
		return nil, false
	}
	return o.PayloadHash, true
}

// HasPayloadHash returns a boolean if a field has been set.
func (o *Event) HasPayloadHash() bool {
	if o != nil && !IsNil(o.PayloadHash) {
		return true
	}

	return false
}

// SetPayloadHash gets a reference to the given string and assigns it to the PayloadHash field.
func (o *Event) SetPayloadHash(v string) {
	o.PayloadHash = &v
}

// GetReceivedAt returns the ReceivedAt field value
func (o *Event) GetReceivedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ReceivedAt
}

// GetReceivedAtOk returns a tuple with the ReceivedAt field value
// and a boolean to check if the value has been set.
func (o *Event) GetReceivedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReceivedAt, true
}

// SetReceivedAt sets field value
func (o *Event) SetReceivedAt(v string) {
	o.ReceivedAt = v
}

// GetSourceId returns the SourceId field value if set, zero value otherwise.
func (o *Event) GetSourceId() string {
	if o == nil || IsNil(o.SourceId) {
		var ret string
		return ret
	}
	return *o.SourceId
}

// GetSourceIdOk returns a tuple with the SourceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetSourceIdOk() (*string, bool) {
	if o == nil || IsNil(o.SourceId) {
		return nil, false
	}
	return o.SourceId, true
}

// HasSourceId returns a boolean if a field has been set.
func (o *Event) HasSourceId() bool {
	if o != nil && !IsNil(o.SourceId) {
		return true
	}

	return false
}

// SetSourceId gets a reference to the given string and assigns it to the SourceId field.
func (o *Event) SetSourceId(v string) {
	o.SourceId = &v
}

// GetStatus returns the Status field value
func (o *Event) GetStatus() EventStatus {
	if o == nil {
		var ret EventStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *Event) GetStatusOk() (*EventStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *Event) SetStatus(v EventStatus) {
	o.Status = v
}

func (o Event) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Event) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["account_id"] = o.AccountId
	toSerialize["attempts_count"] = o.AttemptsCount
	toSerialize["body"] = o.Body
	toSerialize["created_at"] = o.CreatedAt
	if !IsNil(o.CreatedBy) {
		toSerialize["created_by"] = o.CreatedBy
	}
	toSerialize["direction"] = o.Direction
	if !IsNil(o.EventType) {
		toSerialize["event_type"] = o.EventType
	}
	if !IsNil(o.ExternalEventId) {
		toSerialize["external_event_id"] = o.ExternalEventId
	}
	if !IsNil(o.FinalState) {
		toSerialize["final_state"] = o.FinalState
	}
	toSerialize["headers"] = o.Headers
	toSerialize["id"] = o.Id
	if !IsNil(o.NextAttemptAt) {
		toSerialize["next_attempt_at"] = o.NextAttemptAt
	}
	if !IsNil(o.PayloadHash) {
		toSerialize["payload_hash"] = o.PayloadHash
	}
	toSerialize["received_at"] = o.ReceivedAt
	if !IsNil(o.SourceId) {
		toSerialize["source_id"] = o.SourceId
	}
	toSerialize["status"] = o.Status
	return toSerialize, nil
}

func (o *Event) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"account_id",
		"attempts_count",
		"body",
		"created_at",
		"direction",
		"headers",
		"id",
		"received_at",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEvent := _Event{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEvent)

	if err != nil {
		return err
	}

	*o = Event(varEvent)

	return err
}

type NullableEvent struct {
	value *Event
	isSet bool
}

func (v NullableEvent) Get() *Event {
	return v.value
}

func (v *NullableEvent) Set(val *Event) {
	v.value = val
	v.isSet = true
}

func (v NullableEvent) IsSet() bool {
	return v.isSet
}

func (v *NullableEvent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEvent(val *Event) *NullableEvent {
	return &NullableEvent{value: val, isSet: true}
}

func (v NullableEvent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEvent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


