/*
GetHook API

Webhook Reliability Gateway — accept inbound webhooks, persist them durably, forward to destinations, retry failures, and replay past events.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gethook

import (
	"encoding/json"
)

// checks if the UpdateDestinationRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateDestinationRequest{}

// UpdateDestinationRequest struct for UpdateDestinationRequest
type UpdateDestinationRequest struct {
	Active *bool `json:"active,omitempty"`
	AuthConfig map[string]interface{} `json:"auth_config,omitempty"`
	CustomHeaders map[string]interface{} `json:"custom_headers,omitempty"`
	Name *string `json:"name,omitempty"`
	TimeoutSeconds *int32 `json:"timeout_seconds,omitempty"`
	Url *string `json:"url,omitempty"`
}

// NewUpdateDestinationRequest instantiates a new UpdateDestinationRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateDestinationRequest() *UpdateDestinationRequest {
	this := UpdateDestinationRequest{}
	return &this
}

// NewUpdateDestinationRequestWithDefaults instantiates a new UpdateDestinationRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateDestinationRequestWithDefaults() *UpdateDestinationRequest {
	this := UpdateDestinationRequest{}
	return &this
}

// GetActive returns the Active field value if set, zero value otherwise.
func (o *UpdateDestinationRequest) GetActive() bool {
	if o == nil || IsNil(o.Active) {
		var ret bool
		return ret
	}
	return *o.Active
}

// GetActiveOk returns a tuple with the Active field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateDestinationRequest) GetActiveOk() (*bool, bool) {
	if o == nil || IsNil(o.Active) {
		return nil, false
	}
	return o.Active, true
}

// HasActive returns a boolean if a field has been set.
func (o *UpdateDestinationRequest) HasActive() bool {
	if o != nil && !IsNil(o.Active) {
		return true
	}

	return false
}

// SetActive gets a reference to the given bool and assigns it to the Active field.
func (o *UpdateDestinationRequest) SetActive(v bool) {
	o.Active = &v
}

// GetAuthConfig returns the AuthConfig field value if set, zero value otherwise.
func (o *UpdateDestinationRequest) GetAuthConfig() map[string]interface{} {
	if o == nil || IsNil(o.AuthConfig) {
		var ret map[string]interface{}
		return ret
	}
	return o.AuthConfig
}

// GetAuthConfigOk returns a tuple with the AuthConfig field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateDestinationRequest) GetAuthConfigOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.AuthConfig) {
		return map[string]interface{}{}, false
	}
	return o.AuthConfig, true
}

// HasAuthConfig returns a boolean if a field has been set.
func (o *UpdateDestinationRequest) HasAuthConfig() bool {
	if o != nil && !IsNil(o.AuthConfig) {
		return true
	}

	return false
}

// SetAuthConfig gets a reference to the given map[string]interface{} and assigns it to the AuthConfig field.
func (o *UpdateDestinationRequest) SetAuthConfig(v map[string]interface{}) {
	o.AuthConfig = v
}

// GetCustomHeaders returns the CustomHeaders field value if set, zero value otherwise.
func (o *UpdateDestinationRequest) GetCustomHeaders() map[string]interface{} {
	if o == nil || IsNil(o.CustomHeaders) {
		var ret map[string]interface{}
		return ret
	}
	return o.CustomHeaders
}

// GetCustomHeadersOk returns a tuple with the CustomHeaders field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateDestinationRequest) GetCustomHeadersOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.CustomHeaders) {
		return map[string]interface{}{}, false
	}
	return o.CustomHeaders, true
}

// HasCustomHeaders returns a boolean if a field has been set.
func (o *UpdateDestinationRequest) HasCustomHeaders() bool {
	if o != nil && !IsNil(o.CustomHeaders) {
		return true
	}

	return false
}

// SetCustomHeaders gets a reference to the given map[string]interface{} and assigns it to the CustomHeaders field.
func (o *UpdateDestinationRequest) SetCustomHeaders(v map[string]interface{}) {
	o.CustomHeaders = v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *UpdateDestinationRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateDestinationRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *UpdateDestinationRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *UpdateDestinationRequest) SetName(v string) {
	o.Name = &v
}

// GetTimeoutSeconds returns the TimeoutSeconds field value if set, zero value otherwise.
func (o *UpdateDestinationRequest) GetTimeoutSeconds() int32 {
	if o == nil || IsNil(o.TimeoutSeconds) {
		var ret int32
		return ret
	}
	return *o.TimeoutSeconds
}

// GetTimeoutSecondsOk returns a tuple with the TimeoutSeconds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateDestinationRequest) GetTimeoutSecondsOk() (*int32, bool) {
	if o == nil || IsNil(o.TimeoutSeconds) {
		return nil, false
	}
	return o.TimeoutSeconds, true
}

// HasTimeoutSeconds returns a boolean if a field has been set.
func (o *UpdateDestinationRequest) HasTimeoutSeconds() bool {
	if o != nil && !IsNil(o.TimeoutSeconds) {
		return true
	}

	return false
}

// SetTimeoutSeconds gets a reference to the given int32 and assigns it to the TimeoutSeconds field.
func (o *UpdateDestinationRequest) SetTimeoutSeconds(v int32) {
	o.TimeoutSeconds = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *UpdateDestinationRequest) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateDestinationRequest) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *UpdateDestinationRequest) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *UpdateDestinationRequest) SetUrl(v string) {
	o.Url = &v
}

func (o UpdateDestinationRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateDestinationRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Active) {
		toSerialize["active"] = o.Active
	}
	if !IsNil(o.AuthConfig) {
		toSerialize["auth_config"] = o.AuthConfig
	}
	if !IsNil(o.CustomHeaders) {
		toSerialize["custom_headers"] = o.CustomHeaders
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.TimeoutSeconds) {
		toSerialize["timeout_seconds"] = o.TimeoutSeconds
	}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	return toSerialize, nil
}

type NullableUpdateDestinationRequest struct {
	value *UpdateDestinationRequest
	isSet bool
}

func (v NullableUpdateDestinationRequest) Get() *UpdateDestinationRequest {
	return v.value
}

func (v *NullableUpdateDestinationRequest) Set(val *UpdateDestinationRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateDestinationRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateDestinationRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateDestinationRequest(val *UpdateDestinationRequest) *NullableUpdateDestinationRequest {
	return &NullableUpdateDestinationRequest{value: val, isSet: true}
}

func (v NullableUpdateDestinationRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateDestinationRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


