/*
GetHook API

Webhook Reliability Gateway — accept inbound webhooks, persist them durably, forward to destinations, retry failures, and replay past events.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gethook

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PublishOutboundData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PublishOutboundData{}

// PublishOutboundData struct for PublishOutboundData
type PublishOutboundData struct {
	Id string `json:"id"`
	Status string `json:"status"`
}

type _PublishOutboundData PublishOutboundData

// NewPublishOutboundData instantiates a new PublishOutboundData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPublishOutboundData(id string, status string) *PublishOutboundData {
	this := PublishOutboundData{}
	this.Id = id
	this.Status = status
	return &this
}

// NewPublishOutboundDataWithDefaults instantiates a new PublishOutboundData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPublishOutboundDataWithDefaults() *PublishOutboundData {
	this := PublishOutboundData{}
	return &this
}

// GetId returns the Id field value
func (o *PublishOutboundData) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *PublishOutboundData) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *PublishOutboundData) SetId(v string) {
	o.Id = v
}

// GetStatus returns the Status field value
func (o *PublishOutboundData) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *PublishOutboundData) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *PublishOutboundData) SetStatus(v string) {
	o.Status = v
}

func (o PublishOutboundData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PublishOutboundData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["status"] = o.Status
	return toSerialize, nil
}

func (o *PublishOutboundData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPublishOutboundData := _PublishOutboundData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPublishOutboundData)

	if err != nil {
		return err
	}

	*o = PublishOutboundData(varPublishOutboundData)

	return err
}

type NullablePublishOutboundData struct {
	value *PublishOutboundData
	isSet bool
}

func (v NullablePublishOutboundData) Get() *PublishOutboundData {
	return v.value
}

func (v *NullablePublishOutboundData) Set(val *PublishOutboundData) {
	v.value = val
	v.isSet = true
}

func (v NullablePublishOutboundData) IsSet() bool {
	return v.isSet
}

func (v *NullablePublishOutboundData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePublishOutboundData(val *PublishOutboundData) *NullablePublishOutboundData {
	return &NullablePublishOutboundData{value: val, isSet: true}
}

func (v NullablePublishOutboundData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePublishOutboundData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


