/*
GetHook API

Webhook Reliability Gateway — accept inbound webhooks, persist them durably, forward to destinations, retry failures, and replay past events.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gethook

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateCustomDomainRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateCustomDomainRequest{}

// CreateCustomDomainRequest struct for CreateCustomDomainRequest
type CreateCustomDomainRequest struct {
	Domain string `json:"domain"`
	Type *string `json:"type,omitempty"`
}

type _CreateCustomDomainRequest CreateCustomDomainRequest

// NewCreateCustomDomainRequest instantiates a new CreateCustomDomainRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateCustomDomainRequest(domain string) *CreateCustomDomainRequest {
	this := CreateCustomDomainRequest{}
	this.Domain = domain
	return &this
}

// NewCreateCustomDomainRequestWithDefaults instantiates a new CreateCustomDomainRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateCustomDomainRequestWithDefaults() *CreateCustomDomainRequest {
	this := CreateCustomDomainRequest{}
	return &this
}

// GetDomain returns the Domain field value
func (o *CreateCustomDomainRequest) GetDomain() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Domain
}

// GetDomainOk returns a tuple with the Domain field value
// and a boolean to check if the value has been set.
func (o *CreateCustomDomainRequest) GetDomainOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Domain, true
}

// SetDomain sets field value
func (o *CreateCustomDomainRequest) SetDomain(v string) {
	o.Domain = v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *CreateCustomDomainRequest) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateCustomDomainRequest) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *CreateCustomDomainRequest) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *CreateCustomDomainRequest) SetType(v string) {
	o.Type = &v
}

func (o CreateCustomDomainRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateCustomDomainRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["domain"] = o.Domain
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	return toSerialize, nil
}

func (o *CreateCustomDomainRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"domain",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateCustomDomainRequest := _CreateCustomDomainRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateCustomDomainRequest)

	if err != nil {
		return err
	}

	*o = CreateCustomDomainRequest(varCreateCustomDomainRequest)

	return err
}

type NullableCreateCustomDomainRequest struct {
	value *CreateCustomDomainRequest
	isSet bool
}

func (v NullableCreateCustomDomainRequest) Get() *CreateCustomDomainRequest {
	return v.value
}

func (v *NullableCreateCustomDomainRequest) Set(val *CreateCustomDomainRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateCustomDomainRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateCustomDomainRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateCustomDomainRequest(val *CreateCustomDomainRequest) *NullableCreateCustomDomainRequest {
	return &NullableCreateCustomDomainRequest{value: val, isSet: true}
}

func (v NullableCreateCustomDomainRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateCustomDomainRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


