/*
GetHook API

Webhook Reliability Gateway — accept inbound webhooks, persist them durably, forward to destinations, retry failures, and replay past events.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gethook

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the StatsData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StatsData{}

// StatsData struct for StatsData
type StatsData struct {
	ByStatus []StatsStatusItem `json:"by_status"`
	Daily []StatsDailyItem `json:"daily"`
	Totals AggregateTotals `json:"totals"`
}

type _StatsData StatsData

// NewStatsData instantiates a new StatsData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStatsData(byStatus []StatsStatusItem, daily []StatsDailyItem, totals AggregateTotals) *StatsData {
	this := StatsData{}
	this.ByStatus = byStatus
	this.Daily = daily
	this.Totals = totals
	return &this
}

// NewStatsDataWithDefaults instantiates a new StatsData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStatsDataWithDefaults() *StatsData {
	this := StatsData{}
	return &this
}

// GetByStatus returns the ByStatus field value
func (o *StatsData) GetByStatus() []StatsStatusItem {
	if o == nil {
		var ret []StatsStatusItem
		return ret
	}

	return o.ByStatus
}

// GetByStatusOk returns a tuple with the ByStatus field value
// and a boolean to check if the value has been set.
func (o *StatsData) GetByStatusOk() ([]StatsStatusItem, bool) {
	if o == nil {
		return nil, false
	}
	return o.ByStatus, true
}

// SetByStatus sets field value
func (o *StatsData) SetByStatus(v []StatsStatusItem) {
	o.ByStatus = v
}

// GetDaily returns the Daily field value
func (o *StatsData) GetDaily() []StatsDailyItem {
	if o == nil {
		var ret []StatsDailyItem
		return ret
	}

	return o.Daily
}

// GetDailyOk returns a tuple with the Daily field value
// and a boolean to check if the value has been set.
func (o *StatsData) GetDailyOk() ([]StatsDailyItem, bool) {
	if o == nil {
		return nil, false
	}
	return o.Daily, true
}

// SetDaily sets field value
func (o *StatsData) SetDaily(v []StatsDailyItem) {
	o.Daily = v
}

// GetTotals returns the Totals field value
func (o *StatsData) GetTotals() AggregateTotals {
	if o == nil {
		var ret AggregateTotals
		return ret
	}

	return o.Totals
}

// GetTotalsOk returns a tuple with the Totals field value
// and a boolean to check if the value has been set.
func (o *StatsData) GetTotalsOk() (*AggregateTotals, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Totals, true
}

// SetTotals sets field value
func (o *StatsData) SetTotals(v AggregateTotals) {
	o.Totals = v
}

func (o StatsData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StatsData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["by_status"] = o.ByStatus
	toSerialize["daily"] = o.Daily
	toSerialize["totals"] = o.Totals
	return toSerialize, nil
}

func (o *StatsData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"by_status",
		"daily",
		"totals",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varStatsData := _StatsData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varStatsData)

	if err != nil {
		return err
	}

	*o = StatsData(varStatsData)

	return err
}

type NullableStatsData struct {
	value *StatsData
	isSet bool
}

func (v NullableStatsData) Get() *StatsData {
	return v.value
}

func (v *NullableStatsData) Set(val *StatsData) {
	v.value = val
	v.isSet = true
}

func (v NullableStatsData) IsSet() bool {
	return v.isSet
}

func (v *NullableStatsData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStatsData(val *StatsData) *NullableStatsData {
	return &NullableStatsData{value: val, isSet: true}
}

func (v NullableStatsData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStatsData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


