/*
GetHook API

Webhook Reliability Gateway — accept inbound webhooks, persist them durably, forward to destinations, retry failures, and replay past events.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gethook

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CustomDomain type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CustomDomain{}

// CustomDomain struct for CustomDomain
type CustomDomain struct {
	AccountId string `json:"account_id"`
	CreatedAt string `json:"created_at"`
	Domain string `json:"domain"`
	Id string `json:"id"`
	Status string `json:"status"`
	TlsStatus string `json:"tls_status"`
	Type string `json:"type"`
	VerificationToken string `json:"verification_token"`
}

type _CustomDomain CustomDomain

// NewCustomDomain instantiates a new CustomDomain object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCustomDomain(accountId string, createdAt string, domain string, id string, status string, tlsStatus string, type_ string, verificationToken string) *CustomDomain {
	this := CustomDomain{}
	this.AccountId = accountId
	this.CreatedAt = createdAt
	this.Domain = domain
	this.Id = id
	this.Status = status
	this.TlsStatus = tlsStatus
	this.Type = type_
	this.VerificationToken = verificationToken
	return &this
}

// NewCustomDomainWithDefaults instantiates a new CustomDomain object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCustomDomainWithDefaults() *CustomDomain {
	this := CustomDomain{}
	return &this
}

// GetAccountId returns the AccountId field value
func (o *CustomDomain) GetAccountId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value
// and a boolean to check if the value has been set.
func (o *CustomDomain) GetAccountIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccountId, true
}

// SetAccountId sets field value
func (o *CustomDomain) SetAccountId(v string) {
	o.AccountId = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *CustomDomain) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *CustomDomain) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *CustomDomain) SetCreatedAt(v string) {
	o.CreatedAt = v
}

// GetDomain returns the Domain field value
func (o *CustomDomain) GetDomain() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Domain
}

// GetDomainOk returns a tuple with the Domain field value
// and a boolean to check if the value has been set.
func (o *CustomDomain) GetDomainOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Domain, true
}

// SetDomain sets field value
func (o *CustomDomain) SetDomain(v string) {
	o.Domain = v
}

// GetId returns the Id field value
func (o *CustomDomain) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CustomDomain) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CustomDomain) SetId(v string) {
	o.Id = v
}

// GetStatus returns the Status field value
func (o *CustomDomain) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *CustomDomain) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *CustomDomain) SetStatus(v string) {
	o.Status = v
}

// GetTlsStatus returns the TlsStatus field value
func (o *CustomDomain) GetTlsStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TlsStatus
}

// GetTlsStatusOk returns a tuple with the TlsStatus field value
// and a boolean to check if the value has been set.
func (o *CustomDomain) GetTlsStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TlsStatus, true
}

// SetTlsStatus sets field value
func (o *CustomDomain) SetTlsStatus(v string) {
	o.TlsStatus = v
}

// GetType returns the Type field value
func (o *CustomDomain) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *CustomDomain) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *CustomDomain) SetType(v string) {
	o.Type = v
}

// GetVerificationToken returns the VerificationToken field value
func (o *CustomDomain) GetVerificationToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.VerificationToken
}

// GetVerificationTokenOk returns a tuple with the VerificationToken field value
// and a boolean to check if the value has been set.
func (o *CustomDomain) GetVerificationTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VerificationToken, true
}

// SetVerificationToken sets field value
func (o *CustomDomain) SetVerificationToken(v string) {
	o.VerificationToken = v
}

func (o CustomDomain) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CustomDomain) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["account_id"] = o.AccountId
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["domain"] = o.Domain
	toSerialize["id"] = o.Id
	toSerialize["status"] = o.Status
	toSerialize["tls_status"] = o.TlsStatus
	toSerialize["type"] = o.Type
	toSerialize["verification_token"] = o.VerificationToken
	return toSerialize, nil
}

func (o *CustomDomain) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"account_id",
		"created_at",
		"domain",
		"id",
		"status",
		"tls_status",
		"type",
		"verification_token",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCustomDomain := _CustomDomain{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCustomDomain)

	if err != nil {
		return err
	}

	*o = CustomDomain(varCustomDomain)

	return err
}

type NullableCustomDomain struct {
	value *CustomDomain
	isSet bool
}

func (v NullableCustomDomain) Get() *CustomDomain {
	return v.value
}

func (v *NullableCustomDomain) Set(val *CustomDomain) {
	v.value = val
	v.isSet = true
}

func (v NullableCustomDomain) IsSet() bool {
	return v.isSet
}

func (v *NullableCustomDomain) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustomDomain(val *CustomDomain) *NullableCustomDomain {
	return &NullableCustomDomain{value: val, isSet: true}
}

func (v NullableCustomDomain) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustomDomain) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


