/*
GetHook API

Webhook Reliability Gateway — accept inbound webhooks, persist them durably, forward to destinations, retry failures, and replay past events.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gethook

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BrandSettings type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BrandSettings{}

// BrandSettings struct for BrandSettings
type BrandSettings struct {
	AccountId string `json:"account_id"`
	CompanyName *string `json:"company_name,omitempty"`
	CreatedAt string `json:"created_at"`
	DocsTitle *string `json:"docs_title,omitempty"`
	Id string `json:"id"`
	LogoUrl *string `json:"logo_url,omitempty"`
	PrimaryColor *string `json:"primary_color,omitempty"`
	SupportEmail *string `json:"support_email,omitempty"`
	UpdatedAt string `json:"updated_at"`
}

type _BrandSettings BrandSettings

// NewBrandSettings instantiates a new BrandSettings object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBrandSettings(accountId string, createdAt string, id string, updatedAt string) *BrandSettings {
	this := BrandSettings{}
	this.AccountId = accountId
	this.CreatedAt = createdAt
	this.Id = id
	this.UpdatedAt = updatedAt
	return &this
}

// NewBrandSettingsWithDefaults instantiates a new BrandSettings object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBrandSettingsWithDefaults() *BrandSettings {
	this := BrandSettings{}
	return &this
}

// GetAccountId returns the AccountId field value
func (o *BrandSettings) GetAccountId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value
// and a boolean to check if the value has been set.
func (o *BrandSettings) GetAccountIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccountId, true
}

// SetAccountId sets field value
func (o *BrandSettings) SetAccountId(v string) {
	o.AccountId = v
}

// GetCompanyName returns the CompanyName field value if set, zero value otherwise.
func (o *BrandSettings) GetCompanyName() string {
	if o == nil || IsNil(o.CompanyName) {
		var ret string
		return ret
	}
	return *o.CompanyName
}

// GetCompanyNameOk returns a tuple with the CompanyName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BrandSettings) GetCompanyNameOk() (*string, bool) {
	if o == nil || IsNil(o.CompanyName) {
		return nil, false
	}
	return o.CompanyName, true
}

// HasCompanyName returns a boolean if a field has been set.
func (o *BrandSettings) HasCompanyName() bool {
	if o != nil && !IsNil(o.CompanyName) {
		return true
	}

	return false
}

// SetCompanyName gets a reference to the given string and assigns it to the CompanyName field.
func (o *BrandSettings) SetCompanyName(v string) {
	o.CompanyName = &v
}

// GetCreatedAt returns the CreatedAt field value
func (o *BrandSettings) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *BrandSettings) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *BrandSettings) SetCreatedAt(v string) {
	o.CreatedAt = v
}

// GetDocsTitle returns the DocsTitle field value if set, zero value otherwise.
func (o *BrandSettings) GetDocsTitle() string {
	if o == nil || IsNil(o.DocsTitle) {
		var ret string
		return ret
	}
	return *o.DocsTitle
}

// GetDocsTitleOk returns a tuple with the DocsTitle field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BrandSettings) GetDocsTitleOk() (*string, bool) {
	if o == nil || IsNil(o.DocsTitle) {
		return nil, false
	}
	return o.DocsTitle, true
}

// HasDocsTitle returns a boolean if a field has been set.
func (o *BrandSettings) HasDocsTitle() bool {
	if o != nil && !IsNil(o.DocsTitle) {
		return true
	}

	return false
}

// SetDocsTitle gets a reference to the given string and assigns it to the DocsTitle field.
func (o *BrandSettings) SetDocsTitle(v string) {
	o.DocsTitle = &v
}

// GetId returns the Id field value
func (o *BrandSettings) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *BrandSettings) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *BrandSettings) SetId(v string) {
	o.Id = v
}

// GetLogoUrl returns the LogoUrl field value if set, zero value otherwise.
func (o *BrandSettings) GetLogoUrl() string {
	if o == nil || IsNil(o.LogoUrl) {
		var ret string
		return ret
	}
	return *o.LogoUrl
}

// GetLogoUrlOk returns a tuple with the LogoUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BrandSettings) GetLogoUrlOk() (*string, bool) {
	if o == nil || IsNil(o.LogoUrl) {
		return nil, false
	}
	return o.LogoUrl, true
}

// HasLogoUrl returns a boolean if a field has been set.
func (o *BrandSettings) HasLogoUrl() bool {
	if o != nil && !IsNil(o.LogoUrl) {
		return true
	}

	return false
}

// SetLogoUrl gets a reference to the given string and assigns it to the LogoUrl field.
func (o *BrandSettings) SetLogoUrl(v string) {
	o.LogoUrl = &v
}

// GetPrimaryColor returns the PrimaryColor field value if set, zero value otherwise.
func (o *BrandSettings) GetPrimaryColor() string {
	if o == nil || IsNil(o.PrimaryColor) {
		var ret string
		return ret
	}
	return *o.PrimaryColor
}

// GetPrimaryColorOk returns a tuple with the PrimaryColor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BrandSettings) GetPrimaryColorOk() (*string, bool) {
	if o == nil || IsNil(o.PrimaryColor) {
		return nil, false
	}
	return o.PrimaryColor, true
}

// HasPrimaryColor returns a boolean if a field has been set.
func (o *BrandSettings) HasPrimaryColor() bool {
	if o != nil && !IsNil(o.PrimaryColor) {
		return true
	}

	return false
}

// SetPrimaryColor gets a reference to the given string and assigns it to the PrimaryColor field.
func (o *BrandSettings) SetPrimaryColor(v string) {
	o.PrimaryColor = &v
}

// GetSupportEmail returns the SupportEmail field value if set, zero value otherwise.
func (o *BrandSettings) GetSupportEmail() string {
	if o == nil || IsNil(o.SupportEmail) {
		var ret string
		return ret
	}
	return *o.SupportEmail
}

// GetSupportEmailOk returns a tuple with the SupportEmail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BrandSettings) GetSupportEmailOk() (*string, bool) {
	if o == nil || IsNil(o.SupportEmail) {
		return nil, false
	}
	return o.SupportEmail, true
}

// HasSupportEmail returns a boolean if a field has been set.
func (o *BrandSettings) HasSupportEmail() bool {
	if o != nil && !IsNil(o.SupportEmail) {
		return true
	}

	return false
}

// SetSupportEmail gets a reference to the given string and assigns it to the SupportEmail field.
func (o *BrandSettings) SetSupportEmail(v string) {
	o.SupportEmail = &v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *BrandSettings) GetUpdatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *BrandSettings) GetUpdatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *BrandSettings) SetUpdatedAt(v string) {
	o.UpdatedAt = v
}

func (o BrandSettings) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BrandSettings) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["account_id"] = o.AccountId
	if !IsNil(o.CompanyName) {
		toSerialize["company_name"] = o.CompanyName
	}
	toSerialize["created_at"] = o.CreatedAt
	if !IsNil(o.DocsTitle) {
		toSerialize["docs_title"] = o.DocsTitle
	}
	toSerialize["id"] = o.Id
	if !IsNil(o.LogoUrl) {
		toSerialize["logo_url"] = o.LogoUrl
	}
	if !IsNil(o.PrimaryColor) {
		toSerialize["primary_color"] = o.PrimaryColor
	}
	if !IsNil(o.SupportEmail) {
		toSerialize["support_email"] = o.SupportEmail
	}
	toSerialize["updated_at"] = o.UpdatedAt
	return toSerialize, nil
}

func (o *BrandSettings) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"account_id",
		"created_at",
		"id",
		"updated_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBrandSettings := _BrandSettings{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBrandSettings)

	if err != nil {
		return err
	}

	*o = BrandSettings(varBrandSettings)

	return err
}

type NullableBrandSettings struct {
	value *BrandSettings
	isSet bool
}

func (v NullableBrandSettings) Get() *BrandSettings {
	return v.value
}

func (v *NullableBrandSettings) Set(val *BrandSettings) {
	v.value = val
	v.isSet = true
}

func (v NullableBrandSettings) IsSet() bool {
	return v.isSet
}

func (v *NullableBrandSettings) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBrandSettings(val *BrandSettings) *NullableBrandSettings {
	return &NullableBrandSettings{value: val, isSet: true}
}

func (v NullableBrandSettings) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBrandSettings) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


