/*
GetHook API

Webhook Reliability Gateway — accept inbound webhooks, persist them durably, forward to destinations, retry failures, and replay past events.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gethook

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Destination type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Destination{}

// Destination struct for Destination
type Destination struct {
	AccountId string `json:"account_id"`
	Active bool `json:"active"`
	AuthConfig map[string]interface{} `json:"auth_config,omitempty"`
	CreatedAt string `json:"created_at"`
	CustomHeaders map[string]interface{} `json:"custom_headers,omitempty"`
	Id string `json:"id"`
	Name string `json:"name"`
	Preset *string `json:"preset,omitempty"`
	TimeoutSeconds int32 `json:"timeout_seconds"`
	Url string `json:"url"`
}

type _Destination Destination

// NewDestination instantiates a new Destination object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDestination(accountId string, active bool, createdAt string, id string, name string, timeoutSeconds int32, url string) *Destination {
	this := Destination{}
	this.AccountId = accountId
	this.Active = active
	this.CreatedAt = createdAt
	this.Id = id
	this.Name = name
	this.TimeoutSeconds = timeoutSeconds
	this.Url = url
	return &this
}

// NewDestinationWithDefaults instantiates a new Destination object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDestinationWithDefaults() *Destination {
	this := Destination{}
	return &this
}

// GetAccountId returns the AccountId field value
func (o *Destination) GetAccountId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value
// and a boolean to check if the value has been set.
func (o *Destination) GetAccountIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccountId, true
}

// SetAccountId sets field value
func (o *Destination) SetAccountId(v string) {
	o.AccountId = v
}

// GetActive returns the Active field value
func (o *Destination) GetActive() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Active
}

// GetActiveOk returns a tuple with the Active field value
// and a boolean to check if the value has been set.
func (o *Destination) GetActiveOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Active, true
}

// SetActive sets field value
func (o *Destination) SetActive(v bool) {
	o.Active = v
}

// GetAuthConfig returns the AuthConfig field value if set, zero value otherwise.
func (o *Destination) GetAuthConfig() map[string]interface{} {
	if o == nil || IsNil(o.AuthConfig) {
		var ret map[string]interface{}
		return ret
	}
	return o.AuthConfig
}

// GetAuthConfigOk returns a tuple with the AuthConfig field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Destination) GetAuthConfigOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.AuthConfig) {
		return map[string]interface{}{}, false
	}
	return o.AuthConfig, true
}

// HasAuthConfig returns a boolean if a field has been set.
func (o *Destination) HasAuthConfig() bool {
	if o != nil && !IsNil(o.AuthConfig) {
		return true
	}

	return false
}

// SetAuthConfig gets a reference to the given map[string]interface{} and assigns it to the AuthConfig field.
func (o *Destination) SetAuthConfig(v map[string]interface{}) {
	o.AuthConfig = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *Destination) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *Destination) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *Destination) SetCreatedAt(v string) {
	o.CreatedAt = v
}

// GetCustomHeaders returns the CustomHeaders field value if set, zero value otherwise.
func (o *Destination) GetCustomHeaders() map[string]interface{} {
	if o == nil || IsNil(o.CustomHeaders) {
		var ret map[string]interface{}
		return ret
	}
	return o.CustomHeaders
}

// GetCustomHeadersOk returns a tuple with the CustomHeaders field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Destination) GetCustomHeadersOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.CustomHeaders) {
		return map[string]interface{}{}, false
	}
	return o.CustomHeaders, true
}

// HasCustomHeaders returns a boolean if a field has been set.
func (o *Destination) HasCustomHeaders() bool {
	if o != nil && !IsNil(o.CustomHeaders) {
		return true
	}

	return false
}

// SetCustomHeaders gets a reference to the given map[string]interface{} and assigns it to the CustomHeaders field.
func (o *Destination) SetCustomHeaders(v map[string]interface{}) {
	o.CustomHeaders = v
}

// GetId returns the Id field value
func (o *Destination) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *Destination) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *Destination) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *Destination) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *Destination) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *Destination) SetName(v string) {
	o.Name = v
}

// GetPreset returns the Preset field value if set, zero value otherwise.
func (o *Destination) GetPreset() string {
	if o == nil || IsNil(o.Preset) {
		var ret string
		return ret
	}
	return *o.Preset
}

// GetPresetOk returns a tuple with the Preset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Destination) GetPresetOk() (*string, bool) {
	if o == nil || IsNil(o.Preset) {
		return nil, false
	}
	return o.Preset, true
}

// HasPreset returns a boolean if a field has been set.
func (o *Destination) HasPreset() bool {
	if o != nil && !IsNil(o.Preset) {
		return true
	}

	return false
}

// SetPreset gets a reference to the given string and assigns it to the Preset field.
func (o *Destination) SetPreset(v string) {
	o.Preset = &v
}

// GetTimeoutSeconds returns the TimeoutSeconds field value
func (o *Destination) GetTimeoutSeconds() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TimeoutSeconds
}

// GetTimeoutSecondsOk returns a tuple with the TimeoutSeconds field value
// and a boolean to check if the value has been set.
func (o *Destination) GetTimeoutSecondsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TimeoutSeconds, true
}

// SetTimeoutSeconds sets field value
func (o *Destination) SetTimeoutSeconds(v int32) {
	o.TimeoutSeconds = v
}

// GetUrl returns the Url field value
func (o *Destination) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *Destination) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *Destination) SetUrl(v string) {
	o.Url = v
}

func (o Destination) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Destination) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["account_id"] = o.AccountId
	toSerialize["active"] = o.Active
	if !IsNil(o.AuthConfig) {
		toSerialize["auth_config"] = o.AuthConfig
	}
	toSerialize["created_at"] = o.CreatedAt
	if !IsNil(o.CustomHeaders) {
		toSerialize["custom_headers"] = o.CustomHeaders
	}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	if !IsNil(o.Preset) {
		toSerialize["preset"] = o.Preset
	}
	toSerialize["timeout_seconds"] = o.TimeoutSeconds
	toSerialize["url"] = o.Url
	return toSerialize, nil
}

func (o *Destination) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"account_id",
		"active",
		"created_at",
		"id",
		"name",
		"timeout_seconds",
		"url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDestination := _Destination{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDestination)

	if err != nil {
		return err
	}

	*o = Destination(varDestination)

	return err
}

type NullableDestination struct {
	value *Destination
	isSet bool
}

func (v NullableDestination) Get() *Destination {
	return v.value
}

func (v *NullableDestination) Set(val *Destination) {
	v.value = val
	v.isSet = true
}

func (v NullableDestination) IsSet() bool {
	return v.isSet
}

func (v *NullableDestination) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDestination(val *Destination) *NullableDestination {
	return &NullableDestination{value: val, isSet: true}
}

func (v NullableDestination) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDestination) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


