/*
GetHook API

Webhook Reliability Gateway — accept inbound webhooks, persist them durably, forward to destinations, retry failures, and replay past events.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gethook

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PublishOutboundEventRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PublishOutboundEventRequest{}

// PublishOutboundEventRequest struct for PublishOutboundEventRequest
type PublishOutboundEventRequest struct {
	EventType *string `json:"event_type,omitempty"`
	ExternalEventId *string `json:"external_event_id,omitempty"`
	Payload string `json:"payload"`
}

type _PublishOutboundEventRequest PublishOutboundEventRequest

// NewPublishOutboundEventRequest instantiates a new PublishOutboundEventRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPublishOutboundEventRequest(payload string) *PublishOutboundEventRequest {
	this := PublishOutboundEventRequest{}
	this.Payload = payload
	return &this
}

// NewPublishOutboundEventRequestWithDefaults instantiates a new PublishOutboundEventRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPublishOutboundEventRequestWithDefaults() *PublishOutboundEventRequest {
	this := PublishOutboundEventRequest{}
	return &this
}

// GetEventType returns the EventType field value if set, zero value otherwise.
func (o *PublishOutboundEventRequest) GetEventType() string {
	if o == nil || IsNil(o.EventType) {
		var ret string
		return ret
	}
	return *o.EventType
}

// GetEventTypeOk returns a tuple with the EventType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PublishOutboundEventRequest) GetEventTypeOk() (*string, bool) {
	if o == nil || IsNil(o.EventType) {
		return nil, false
	}
	return o.EventType, true
}

// HasEventType returns a boolean if a field has been set.
func (o *PublishOutboundEventRequest) HasEventType() bool {
	if o != nil && !IsNil(o.EventType) {
		return true
	}

	return false
}

// SetEventType gets a reference to the given string and assigns it to the EventType field.
func (o *PublishOutboundEventRequest) SetEventType(v string) {
	o.EventType = &v
}

// GetExternalEventId returns the ExternalEventId field value if set, zero value otherwise.
func (o *PublishOutboundEventRequest) GetExternalEventId() string {
	if o == nil || IsNil(o.ExternalEventId) {
		var ret string
		return ret
	}
	return *o.ExternalEventId
}

// GetExternalEventIdOk returns a tuple with the ExternalEventId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PublishOutboundEventRequest) GetExternalEventIdOk() (*string, bool) {
	if o == nil || IsNil(o.ExternalEventId) {
		return nil, false
	}
	return o.ExternalEventId, true
}

// HasExternalEventId returns a boolean if a field has been set.
func (o *PublishOutboundEventRequest) HasExternalEventId() bool {
	if o != nil && !IsNil(o.ExternalEventId) {
		return true
	}

	return false
}

// SetExternalEventId gets a reference to the given string and assigns it to the ExternalEventId field.
func (o *PublishOutboundEventRequest) SetExternalEventId(v string) {
	o.ExternalEventId = &v
}

// GetPayload returns the Payload field value
func (o *PublishOutboundEventRequest) GetPayload() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Payload
}

// GetPayloadOk returns a tuple with the Payload field value
// and a boolean to check if the value has been set.
func (o *PublishOutboundEventRequest) GetPayloadOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Payload, true
}

// SetPayload sets field value
func (o *PublishOutboundEventRequest) SetPayload(v string) {
	o.Payload = v
}

func (o PublishOutboundEventRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PublishOutboundEventRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.EventType) {
		toSerialize["event_type"] = o.EventType
	}
	if !IsNil(o.ExternalEventId) {
		toSerialize["external_event_id"] = o.ExternalEventId
	}
	toSerialize["payload"] = o.Payload
	return toSerialize, nil
}

func (o *PublishOutboundEventRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"payload",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPublishOutboundEventRequest := _PublishOutboundEventRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPublishOutboundEventRequest)

	if err != nil {
		return err
	}

	*o = PublishOutboundEventRequest(varPublishOutboundEventRequest)

	return err
}

type NullablePublishOutboundEventRequest struct {
	value *PublishOutboundEventRequest
	isSet bool
}

func (v NullablePublishOutboundEventRequest) Get() *PublishOutboundEventRequest {
	return v.value
}

func (v *NullablePublishOutboundEventRequest) Set(val *PublishOutboundEventRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePublishOutboundEventRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePublishOutboundEventRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePublishOutboundEventRequest(val *PublishOutboundEventRequest) *NullablePublishOutboundEventRequest {
	return &NullablePublishOutboundEventRequest{value: val, isSet: true}
}

func (v NullablePublishOutboundEventRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePublishOutboundEventRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


