/*
GetHook API

Webhook Reliability Gateway — accept inbound webhooks, persist them durably, forward to destinations, retry failures, and replay past events.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gethook

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the IngestAcceptedData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IngestAcceptedData{}

// IngestAcceptedData struct for IngestAcceptedData
type IngestAcceptedData struct {
	Id string `json:"id"`
	Status string `json:"status"`
}

type _IngestAcceptedData IngestAcceptedData

// NewIngestAcceptedData instantiates a new IngestAcceptedData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIngestAcceptedData(id string, status string) *IngestAcceptedData {
	this := IngestAcceptedData{}
	this.Id = id
	this.Status = status
	return &this
}

// NewIngestAcceptedDataWithDefaults instantiates a new IngestAcceptedData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIngestAcceptedDataWithDefaults() *IngestAcceptedData {
	this := IngestAcceptedData{}
	return &this
}

// GetId returns the Id field value
func (o *IngestAcceptedData) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *IngestAcceptedData) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *IngestAcceptedData) SetId(v string) {
	o.Id = v
}

// GetStatus returns the Status field value
func (o *IngestAcceptedData) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *IngestAcceptedData) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *IngestAcceptedData) SetStatus(v string) {
	o.Status = v
}

func (o IngestAcceptedData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IngestAcceptedData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["status"] = o.Status
	return toSerialize, nil
}

func (o *IngestAcceptedData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varIngestAcceptedData := _IngestAcceptedData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varIngestAcceptedData)

	if err != nil {
		return err
	}

	*o = IngestAcceptedData(varIngestAcceptedData)

	return err
}

type NullableIngestAcceptedData struct {
	value *IngestAcceptedData
	isSet bool
}

func (v NullableIngestAcceptedData) Get() *IngestAcceptedData {
	return v.value
}

func (v *NullableIngestAcceptedData) Set(val *IngestAcceptedData) {
	v.value = val
	v.isSet = true
}

func (v NullableIngestAcceptedData) IsSet() bool {
	return v.isSet
}

func (v *NullableIngestAcceptedData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIngestAcceptedData(val *IngestAcceptedData) *NullableIngestAcceptedData {
	return &NullableIngestAcceptedData{value: val, isSet: true}
}

func (v NullableIngestAcceptedData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIngestAcceptedData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


