/*
GetHook API

Webhook Reliability Gateway — accept inbound webhooks, persist them durably, forward to destinations, retry failures, and replay past events.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gethook

import (
	"encoding/json"
	"fmt"
)

// AttemptOutcome the model 'AttemptOutcome'
type AttemptOutcome string

// List of AttemptOutcome
const (
	ATTEMPTOUTCOME_OutcomePending AttemptOutcome = "pending"
	ATTEMPTOUTCOME_OutcomeSuccess AttemptOutcome = "success"
	ATTEMPTOUTCOME_OutcomeTimeout AttemptOutcome = "timeout"
	ATTEMPTOUTCOME_OutcomeNetworkError AttemptOutcome = "network_error"
	ATTEMPTOUTCOME_OutcomeHTTP4xx AttemptOutcome = "http_4xx"
	ATTEMPTOUTCOME_OutcomeHTTP5xx AttemptOutcome = "http_5xx"
	ATTEMPTOUTCOME_OutcomeCancelled AttemptOutcome = "cancelled"
)

// All allowed values of AttemptOutcome enum
var AllowedAttemptOutcomeEnumValues = []AttemptOutcome{
	"pending",
	"success",
	"timeout",
	"network_error",
	"http_4xx",
	"http_5xx",
	"cancelled",
}

func (v *AttemptOutcome) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := AttemptOutcome(value)
	for _, existing := range AllowedAttemptOutcomeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid AttemptOutcome", value)
}

// NewAttemptOutcomeFromValue returns a pointer to a valid AttemptOutcome
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewAttemptOutcomeFromValue(v string) (*AttemptOutcome, error) {
	ev := AttemptOutcome(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for AttemptOutcome: valid values are %v", v, AllowedAttemptOutcomeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v AttemptOutcome) IsValid() bool {
	for _, existing := range AllowedAttemptOutcomeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to AttemptOutcome value
func (v AttemptOutcome) Ptr() *AttemptOutcome {
	return &v
}

type NullableAttemptOutcome struct {
	value *AttemptOutcome
	isSet bool
}

func (v NullableAttemptOutcome) Get() *AttemptOutcome {
	return v.value
}

func (v *NullableAttemptOutcome) Set(val *AttemptOutcome) {
	v.value = val
	v.isSet = true
}

func (v NullableAttemptOutcome) IsSet() bool {
	return v.isSet
}

func (v *NullableAttemptOutcome) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAttemptOutcome(val *AttemptOutcome) *NullableAttemptOutcome {
	return &NullableAttemptOutcome{value: val, isSet: true}
}

func (v NullableAttemptOutcome) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAttemptOutcome) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

