/*
GetHook API

Webhook Reliability Gateway — accept inbound webhooks, persist them durably, forward to destinations, retry failures, and replay past events.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gethook

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the APIKeyWithSecret type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &APIKeyWithSecret{}

// APIKeyWithSecret struct for APIKeyWithSecret
type APIKeyWithSecret struct {
	Id string `json:"id"`
	AccountId string `json:"account_id"`
	UserId *string `json:"user_id,omitempty"`
	Name string `json:"name"`
	Role string `json:"role"`
	KeyPrefix string `json:"key_prefix"`
	CreatedAt string `json:"created_at"`
	RevokedAt *string `json:"revoked_at,omitempty"`
	// Full plaintext key — returned once at creation time only.
	Key string `json:"key"`
}

type _APIKeyWithSecret APIKeyWithSecret

// NewAPIKeyWithSecret instantiates a new APIKeyWithSecret object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAPIKeyWithSecret(id string, accountId string, name string, role string, keyPrefix string, createdAt string, key string) *APIKeyWithSecret {
	this := APIKeyWithSecret{}
	this.Id = id
	this.AccountId = accountId
	this.Name = name
	this.Role = role
	this.KeyPrefix = keyPrefix
	this.CreatedAt = createdAt
	this.Key = key
	return &this
}

// NewAPIKeyWithSecretWithDefaults instantiates a new APIKeyWithSecret object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAPIKeyWithSecretWithDefaults() *APIKeyWithSecret {
	this := APIKeyWithSecret{}
	return &this
}

// GetId returns the Id field value
func (o *APIKeyWithSecret) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *APIKeyWithSecret) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *APIKeyWithSecret) SetId(v string) {
	o.Id = v
}

// GetAccountId returns the AccountId field value
func (o *APIKeyWithSecret) GetAccountId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value
// and a boolean to check if the value has been set.
func (o *APIKeyWithSecret) GetAccountIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccountId, true
}

// SetAccountId sets field value
func (o *APIKeyWithSecret) SetAccountId(v string) {
	o.AccountId = v
}

// GetUserId returns the UserId field value if set, zero value otherwise.
func (o *APIKeyWithSecret) GetUserId() string {
	if o == nil || IsNil(o.UserId) {
		var ret string
		return ret
	}
	return *o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIKeyWithSecret) GetUserIdOk() (*string, bool) {
	if o == nil || IsNil(o.UserId) {
		return nil, false
	}
	return o.UserId, true
}

// HasUserId returns a boolean if a field has been set.
func (o *APIKeyWithSecret) HasUserId() bool {
	if o != nil && !IsNil(o.UserId) {
		return true
	}

	return false
}

// SetUserId gets a reference to the given string and assigns it to the UserId field.
func (o *APIKeyWithSecret) SetUserId(v string) {
	o.UserId = &v
}

// GetName returns the Name field value
func (o *APIKeyWithSecret) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *APIKeyWithSecret) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *APIKeyWithSecret) SetName(v string) {
	o.Name = v
}

// GetRole returns the Role field value
func (o *APIKeyWithSecret) GetRole() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Role
}

// GetRoleOk returns a tuple with the Role field value
// and a boolean to check if the value has been set.
func (o *APIKeyWithSecret) GetRoleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Role, true
}

// SetRole sets field value
func (o *APIKeyWithSecret) SetRole(v string) {
	o.Role = v
}

// GetKeyPrefix returns the KeyPrefix field value
func (o *APIKeyWithSecret) GetKeyPrefix() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.KeyPrefix
}

// GetKeyPrefixOk returns a tuple with the KeyPrefix field value
// and a boolean to check if the value has been set.
func (o *APIKeyWithSecret) GetKeyPrefixOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.KeyPrefix, true
}

// SetKeyPrefix sets field value
func (o *APIKeyWithSecret) SetKeyPrefix(v string) {
	o.KeyPrefix = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *APIKeyWithSecret) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *APIKeyWithSecret) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *APIKeyWithSecret) SetCreatedAt(v string) {
	o.CreatedAt = v
}

// GetRevokedAt returns the RevokedAt field value if set, zero value otherwise.
func (o *APIKeyWithSecret) GetRevokedAt() string {
	if o == nil || IsNil(o.RevokedAt) {
		var ret string
		return ret
	}
	return *o.RevokedAt
}

// GetRevokedAtOk returns a tuple with the RevokedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIKeyWithSecret) GetRevokedAtOk() (*string, bool) {
	if o == nil || IsNil(o.RevokedAt) {
		return nil, false
	}
	return o.RevokedAt, true
}

// HasRevokedAt returns a boolean if a field has been set.
func (o *APIKeyWithSecret) HasRevokedAt() bool {
	if o != nil && !IsNil(o.RevokedAt) {
		return true
	}

	return false
}

// SetRevokedAt gets a reference to the given string and assigns it to the RevokedAt field.
func (o *APIKeyWithSecret) SetRevokedAt(v string) {
	o.RevokedAt = &v
}

// GetKey returns the Key field value
func (o *APIKeyWithSecret) GetKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *APIKeyWithSecret) GetKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *APIKeyWithSecret) SetKey(v string) {
	o.Key = v
}

func (o APIKeyWithSecret) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o APIKeyWithSecret) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["account_id"] = o.AccountId
	if !IsNil(o.UserId) {
		toSerialize["user_id"] = o.UserId
	}
	toSerialize["name"] = o.Name
	toSerialize["role"] = o.Role
	toSerialize["key_prefix"] = o.KeyPrefix
	toSerialize["created_at"] = o.CreatedAt
	if !IsNil(o.RevokedAt) {
		toSerialize["revoked_at"] = o.RevokedAt
	}
	toSerialize["key"] = o.Key
	return toSerialize, nil
}

func (o *APIKeyWithSecret) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"account_id",
		"name",
		"role",
		"key_prefix",
		"created_at",
		"key",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAPIKeyWithSecret := _APIKeyWithSecret{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAPIKeyWithSecret)

	if err != nil {
		return err
	}

	*o = APIKeyWithSecret(varAPIKeyWithSecret)

	return err
}

type NullableAPIKeyWithSecret struct {
	value *APIKeyWithSecret
	isSet bool
}

func (v NullableAPIKeyWithSecret) Get() *APIKeyWithSecret {
	return v.value
}

func (v *NullableAPIKeyWithSecret) Set(val *APIKeyWithSecret) {
	v.value = val
	v.isSet = true
}

func (v NullableAPIKeyWithSecret) IsSet() bool {
	return v.isSet
}

func (v *NullableAPIKeyWithSecret) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAPIKeyWithSecret(val *APIKeyWithSecret) *NullableAPIKeyWithSecret {
	return &NullableAPIKeyWithSecret{value: val, isSet: true}
}

func (v NullableAPIKeyWithSecret) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAPIKeyWithSecret) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


