/*
GetHook API

Webhook Reliability Gateway — accept inbound webhooks, persist them durably, forward to destinations, retry failures, and replay past events.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gethook

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AggregateTotals type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AggregateTotals{}

// AggregateTotals Authoritative event totals derived from event_daily_stats (past days) plus live events (today). Accurate even after events are purged by the retention cleaner. 
type AggregateTotals struct {
	Total int32 `json:"total"`
	Delivered int32 `json:"delivered"`
	Failed int32 `json:"failed"`
}

type _AggregateTotals AggregateTotals

// NewAggregateTotals instantiates a new AggregateTotals object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAggregateTotals(total int32, delivered int32, failed int32) *AggregateTotals {
	this := AggregateTotals{}
	this.Total = total
	this.Delivered = delivered
	this.Failed = failed
	return &this
}

// NewAggregateTotalsWithDefaults instantiates a new AggregateTotals object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAggregateTotalsWithDefaults() *AggregateTotals {
	this := AggregateTotals{}
	return &this
}

// GetTotal returns the Total field value
func (o *AggregateTotals) GetTotal() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *AggregateTotals) GetTotalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *AggregateTotals) SetTotal(v int32) {
	o.Total = v
}

// GetDelivered returns the Delivered field value
func (o *AggregateTotals) GetDelivered() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Delivered
}

// GetDeliveredOk returns a tuple with the Delivered field value
// and a boolean to check if the value has been set.
func (o *AggregateTotals) GetDeliveredOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Delivered, true
}

// SetDelivered sets field value
func (o *AggregateTotals) SetDelivered(v int32) {
	o.Delivered = v
}

// GetFailed returns the Failed field value
func (o *AggregateTotals) GetFailed() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Failed
}

// GetFailedOk returns a tuple with the Failed field value
// and a boolean to check if the value has been set.
func (o *AggregateTotals) GetFailedOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Failed, true
}

// SetFailed sets field value
func (o *AggregateTotals) SetFailed(v int32) {
	o.Failed = v
}

func (o AggregateTotals) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AggregateTotals) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["total"] = o.Total
	toSerialize["delivered"] = o.Delivered
	toSerialize["failed"] = o.Failed
	return toSerialize, nil
}

func (o *AggregateTotals) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"total",
		"delivered",
		"failed",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAggregateTotals := _AggregateTotals{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAggregateTotals)

	if err != nil {
		return err
	}

	*o = AggregateTotals(varAggregateTotals)

	return err
}

type NullableAggregateTotals struct {
	value *AggregateTotals
	isSet bool
}

func (v NullableAggregateTotals) Get() *AggregateTotals {
	return v.value
}

func (v *NullableAggregateTotals) Set(val *AggregateTotals) {
	v.value = val
	v.isSet = true
}

func (v NullableAggregateTotals) IsSet() bool {
	return v.isSet
}

func (v *NullableAggregateTotals) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAggregateTotals(val *AggregateTotals) *NullableAggregateTotals {
	return &NullableAggregateTotals{value: val, isSet: true}
}

func (v NullableAggregateTotals) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAggregateTotals) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


