/*
GetHook API

Webhook Reliability Gateway — accept inbound webhooks, persist them durably, forward to destinations, retry failures, and replay past events.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gethook

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EventListData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EventListData{}

// EventListData struct for EventListData
type EventListData struct {
	Items []Event `json:"items"`
	Total int32 `json:"total"`
}

type _EventListData EventListData

// NewEventListData instantiates a new EventListData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEventListData(items []Event, total int32) *EventListData {
	this := EventListData{}
	this.Items = items
	this.Total = total
	return &this
}

// NewEventListDataWithDefaults instantiates a new EventListData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEventListDataWithDefaults() *EventListData {
	this := EventListData{}
	return &this
}

// GetItems returns the Items field value
func (o *EventListData) GetItems() []Event {
	if o == nil {
		var ret []Event
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *EventListData) GetItemsOk() ([]Event, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *EventListData) SetItems(v []Event) {
	o.Items = v
}

// GetTotal returns the Total field value
func (o *EventListData) GetTotal() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *EventListData) GetTotalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *EventListData) SetTotal(v int32) {
	o.Total = v
}

func (o EventListData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EventListData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["items"] = o.Items
	toSerialize["total"] = o.Total
	return toSerialize, nil
}

func (o *EventListData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"items",
		"total",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEventListData := _EventListData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEventListData)

	if err != nil {
		return err
	}

	*o = EventListData(varEventListData)

	return err
}

type NullableEventListData struct {
	value *EventListData
	isSet bool
}

func (v NullableEventListData) Get() *EventListData {
	return v.value
}

func (v *NullableEventListData) Set(val *EventListData) {
	v.value = val
	v.isSet = true
}

func (v NullableEventListData) IsSet() bool {
	return v.isSet
}

func (v *NullableEventListData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEventListData(val *EventListData) *NullableEventListData {
	return &NullableEventListData{value: val, isSet: true}
}

func (v NullableEventListData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEventListData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


