/*
GetHook API

Webhook Reliability Gateway — accept inbound webhooks, persist them durably, forward to destinations, retry failures, and replay past events.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gethook

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EventDetailData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EventDetailData{}

// EventDetailData struct for EventDetailData
type EventDetailData struct {
	Attempts []DeliveryAttempt `json:"attempts"`
	Event Event `json:"event"`
}

type _EventDetailData EventDetailData

// NewEventDetailData instantiates a new EventDetailData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEventDetailData(attempts []DeliveryAttempt, event Event) *EventDetailData {
	this := EventDetailData{}
	this.Attempts = attempts
	this.Event = event
	return &this
}

// NewEventDetailDataWithDefaults instantiates a new EventDetailData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEventDetailDataWithDefaults() *EventDetailData {
	this := EventDetailData{}
	return &this
}

// GetAttempts returns the Attempts field value
func (o *EventDetailData) GetAttempts() []DeliveryAttempt {
	if o == nil {
		var ret []DeliveryAttempt
		return ret
	}

	return o.Attempts
}

// GetAttemptsOk returns a tuple with the Attempts field value
// and a boolean to check if the value has been set.
func (o *EventDetailData) GetAttemptsOk() ([]DeliveryAttempt, bool) {
	if o == nil {
		return nil, false
	}
	return o.Attempts, true
}

// SetAttempts sets field value
func (o *EventDetailData) SetAttempts(v []DeliveryAttempt) {
	o.Attempts = v
}

// GetEvent returns the Event field value
func (o *EventDetailData) GetEvent() Event {
	if o == nil {
		var ret Event
		return ret
	}

	return o.Event
}

// GetEventOk returns a tuple with the Event field value
// and a boolean to check if the value has been set.
func (o *EventDetailData) GetEventOk() (*Event, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Event, true
}

// SetEvent sets field value
func (o *EventDetailData) SetEvent(v Event) {
	o.Event = v
}

func (o EventDetailData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EventDetailData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["attempts"] = o.Attempts
	toSerialize["event"] = o.Event
	return toSerialize, nil
}

func (o *EventDetailData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"attempts",
		"event",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEventDetailData := _EventDetailData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEventDetailData)

	if err != nil {
		return err
	}

	*o = EventDetailData(varEventDetailData)

	return err
}

type NullableEventDetailData struct {
	value *EventDetailData
	isSet bool
}

func (v NullableEventDetailData) Get() *EventDetailData {
	return v.value
}

func (v *NullableEventDetailData) Set(val *EventDetailData) {
	v.value = val
	v.isSet = true
}

func (v NullableEventDetailData) IsSet() bool {
	return v.isSet
}

func (v *NullableEventDetailData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEventDetailData(val *EventDetailData) *NullableEventDetailData {
	return &NullableEventDetailData{value: val, isSet: true}
}

func (v NullableEventDetailData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEventDetailData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


