/*
GetHook API

Webhook Reliability Gateway — accept inbound webhooks, persist them durably, forward to destinations, retry failures, and replay past events.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gethook

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the APIKey type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &APIKey{}

// APIKey struct for APIKey
type APIKey struct {
	AccountId string `json:"account_id"`
	CreatedAt string `json:"created_at"`
	Id string `json:"id"`
	KeyPrefix string `json:"key_prefix"`
	Name string `json:"name"`
	RevokedAt *string `json:"revoked_at,omitempty"`
}

type _APIKey APIKey

// NewAPIKey instantiates a new APIKey object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAPIKey(accountId string, createdAt string, id string, keyPrefix string, name string) *APIKey {
	this := APIKey{}
	this.AccountId = accountId
	this.CreatedAt = createdAt
	this.Id = id
	this.KeyPrefix = keyPrefix
	this.Name = name
	return &this
}

// NewAPIKeyWithDefaults instantiates a new APIKey object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAPIKeyWithDefaults() *APIKey {
	this := APIKey{}
	return &this
}

// GetAccountId returns the AccountId field value
func (o *APIKey) GetAccountId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value
// and a boolean to check if the value has been set.
func (o *APIKey) GetAccountIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccountId, true
}

// SetAccountId sets field value
func (o *APIKey) SetAccountId(v string) {
	o.AccountId = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *APIKey) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *APIKey) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *APIKey) SetCreatedAt(v string) {
	o.CreatedAt = v
}

// GetId returns the Id field value
func (o *APIKey) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *APIKey) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *APIKey) SetId(v string) {
	o.Id = v
}

// GetKeyPrefix returns the KeyPrefix field value
func (o *APIKey) GetKeyPrefix() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.KeyPrefix
}

// GetKeyPrefixOk returns a tuple with the KeyPrefix field value
// and a boolean to check if the value has been set.
func (o *APIKey) GetKeyPrefixOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.KeyPrefix, true
}

// SetKeyPrefix sets field value
func (o *APIKey) SetKeyPrefix(v string) {
	o.KeyPrefix = v
}

// GetName returns the Name field value
func (o *APIKey) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *APIKey) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *APIKey) SetName(v string) {
	o.Name = v
}

// GetRevokedAt returns the RevokedAt field value if set, zero value otherwise.
func (o *APIKey) GetRevokedAt() string {
	if o == nil || IsNil(o.RevokedAt) {
		var ret string
		return ret
	}
	return *o.RevokedAt
}

// GetRevokedAtOk returns a tuple with the RevokedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIKey) GetRevokedAtOk() (*string, bool) {
	if o == nil || IsNil(o.RevokedAt) {
		return nil, false
	}
	return o.RevokedAt, true
}

// HasRevokedAt returns a boolean if a field has been set.
func (o *APIKey) HasRevokedAt() bool {
	if o != nil && !IsNil(o.RevokedAt) {
		return true
	}

	return false
}

// SetRevokedAt gets a reference to the given string and assigns it to the RevokedAt field.
func (o *APIKey) SetRevokedAt(v string) {
	o.RevokedAt = &v
}

func (o APIKey) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o APIKey) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["account_id"] = o.AccountId
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["id"] = o.Id
	toSerialize["key_prefix"] = o.KeyPrefix
	toSerialize["name"] = o.Name
	if !IsNil(o.RevokedAt) {
		toSerialize["revoked_at"] = o.RevokedAt
	}
	return toSerialize, nil
}

func (o *APIKey) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"account_id",
		"created_at",
		"id",
		"key_prefix",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAPIKey := _APIKey{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAPIKey)

	if err != nil {
		return err
	}

	*o = APIKey(varAPIKey)

	return err
}

type NullableAPIKey struct {
	value *APIKey
	isSet bool
}

func (v NullableAPIKey) Get() *APIKey {
	return v.value
}

func (v *NullableAPIKey) Set(val *APIKey) {
	v.value = val
	v.isSet = true
}

func (v NullableAPIKey) IsSet() bool {
	return v.isSet
}

func (v *NullableAPIKey) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAPIKey(val *APIKey) *NullableAPIKey {
	return &NullableAPIKey{value: val, isSet: true}
}

func (v NullableAPIKey) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAPIKey) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


