/*
GetHook API

Webhook Reliability Gateway — accept inbound webhooks, persist them durably, forward to destinations, retry failures, and replay past events.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gethook

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AccountBootstrapData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AccountBootstrapData{}

// AccountBootstrapData struct for AccountBootstrapData
type AccountBootstrapData struct {
	Account Account `json:"account"`
	ApiKey APIKeyWithSecret `json:"api_key"`
}

type _AccountBootstrapData AccountBootstrapData

// NewAccountBootstrapData instantiates a new AccountBootstrapData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccountBootstrapData(account Account, apiKey APIKeyWithSecret) *AccountBootstrapData {
	this := AccountBootstrapData{}
	this.Account = account
	this.ApiKey = apiKey
	return &this
}

// NewAccountBootstrapDataWithDefaults instantiates a new AccountBootstrapData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccountBootstrapDataWithDefaults() *AccountBootstrapData {
	this := AccountBootstrapData{}
	return &this
}

// GetAccount returns the Account field value
func (o *AccountBootstrapData) GetAccount() Account {
	if o == nil {
		var ret Account
		return ret
	}

	return o.Account
}

// GetAccountOk returns a tuple with the Account field value
// and a boolean to check if the value has been set.
func (o *AccountBootstrapData) GetAccountOk() (*Account, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Account, true
}

// SetAccount sets field value
func (o *AccountBootstrapData) SetAccount(v Account) {
	o.Account = v
}

// GetApiKey returns the ApiKey field value
func (o *AccountBootstrapData) GetApiKey() APIKeyWithSecret {
	if o == nil {
		var ret APIKeyWithSecret
		return ret
	}

	return o.ApiKey
}

// GetApiKeyOk returns a tuple with the ApiKey field value
// and a boolean to check if the value has been set.
func (o *AccountBootstrapData) GetApiKeyOk() (*APIKeyWithSecret, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ApiKey, true
}

// SetApiKey sets field value
func (o *AccountBootstrapData) SetApiKey(v APIKeyWithSecret) {
	o.ApiKey = v
}

func (o AccountBootstrapData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AccountBootstrapData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["account"] = o.Account
	toSerialize["api_key"] = o.ApiKey
	return toSerialize, nil
}

func (o *AccountBootstrapData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"account",
		"api_key",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAccountBootstrapData := _AccountBootstrapData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAccountBootstrapData)

	if err != nil {
		return err
	}

	*o = AccountBootstrapData(varAccountBootstrapData)

	return err
}

type NullableAccountBootstrapData struct {
	value *AccountBootstrapData
	isSet bool
}

func (v NullableAccountBootstrapData) Get() *AccountBootstrapData {
	return v.value
}

func (v *NullableAccountBootstrapData) Set(val *AccountBootstrapData) {
	v.value = val
	v.isSet = true
}

func (v NullableAccountBootstrapData) IsSet() bool {
	return v.isSet
}

func (v *NullableAccountBootstrapData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccountBootstrapData(val *AccountBootstrapData) *NullableAccountBootstrapData {
	return &NullableAccountBootstrapData{value: val, isSet: true}
}

func (v NullableAccountBootstrapData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccountBootstrapData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


